### ISSUE TITLE
Dead link in the Mint MATE 20 64-bit installer

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20-beta#10]
The link "notes de publications" is a dead link.

![84587722-f83b2180-ae21-11ea-9d18-3e17763ed56d](https://user-images.githubusercontent.com/3955499/84589017-26256380-ae2c-11ea-8a46-2b9cf3ada2c9.png)

**Comment by xenopeek** [comment]
The link itself is fine. If however you haven't opened Firefox yet, it will take some time before clicking the link appears to do anything because first Firefox has to be loaded. It's not dead, it's slow if Firefox isn't open.

**Comment by InfoLibre** [comment]
I tested Mint 20 before this page was published. It works now, indeed.
