### ISSUE TITLE
Cinnamon: configuration button for Window list applet is greyed out

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/mint20-beta#101]
Cinnamon: the configuration button for the Window list applet is greyed out.

**Comment by xenopeek** [comment]
The configure button on the Window list applet is greyed out if you haven't added it to your panel (can't configure what's not there). The default panel has the Grouped window list applet, not the Window list applet.

I can't reproduce your issue other than as noted when not having the Window list applet on the panel.
