### ISSUE TITLE
Cinnamon: scrolling direction can't be reversed

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/mint20-beta#102]
Cinnamon: when you enable "Reverse scrolling direction" in Mouse and Touchpad, nothing happens. The original scrolling direction remains the same.

**Comment by xenopeek** [comment]
I can't reproduce this yet. After I toggle that option, using my mousewheel scrolls text in Xed in the reverse direction.

How are you scrolling and in which program?

**Comment by NikoKrause** [comment]
I can't reproduce it either. But at first I thought it was broken too. Be aware, that there are two "Reverse scrolling direction" switches. One switch is in the mouse settings and one switch is in the touchpad settings.

**Comment by Pjotr123** [comment]
@NikoKrause: that's indeed the cause of the problem: separate scrolling direction switches for mouse and touchpad. Now it works as intended. Thanks!

I'll open a separate issue for the illogical and non-intuitive existence of two *separately functioning* switches: they should be linked, so that there can't be difference.

**Comment by xenopeek** [comment]
> I'll open a separate issue for the illogical and non-intuitive existence of two separately functioning switches: they should be linked, so that there can't be difference.

Cue a issue to make them separate again for people that do have a reason to have different settings between the two. I think it would be better to make it more clear there are two settings; perhaps having them together in one place.

**Comment by NikoKrause** [comment]
I don't think, that it's illogical, though. I think the opposite is the case: It is really logical.

You maybe like to have a different scrolling behaviour for your mouse than for your touchpad. Also if you scroll with your touchpad, you look in the touchpad settings, not the mouse settings.
