### ISSUE TITLE
XFCE version. Strange volume slider “pop up” 

### ISSUE THREAD

**Issue by ewan777** [linuxmint/mint20-beta#104]
XFCE version. Strange volume slider “pop up”  when using the volume slider on main panel. The pop-up blocks access to the real volume slider.

**Comment by xenopeek** [comment]
Can you add a screenshot showing the issue? Open the Screenshot program from your menu, set a delay of couple of seconds, click OK and reproduce the issue. Once the screenshot is taken you can copy it to clipboard and paste it here in a comment.

Here's how it looks on the LiveISO when using the slider:
![image](https://user-images.githubusercontent.com/21159972/84983832-e2876e00-b139-11ea-86d9-10c7acbdbc95.png)

**Comment by ewan777** [comment]
As can be seen, when the panel is at the top of screen, the "pop up" slider blocks the underlying volume applet. Not sure what is going on here, I have Xubuntu on my other laptop and this behavior isn't observed.

![Screenshot_2020-06-20_02-22-18](https://user-images.githubusercontent.com/10433140/85188244-1f1faa80-b29d-11ea-85ba-01552c9010b5.png)

**Comment by MrEen-Mint** [comment]
If you change Menu > Settings > Notifications > Default Position to something other than Top right, does that allow you access to the slider?

**Comment by xenopeek** [comment]
Indeed, if you reorient the panel to the top you would reorient the notifications to fit your preference and not overlap. Click on the bell icon in your panel, select Notification settings and change the Default position from Top right to something other.

**Comment by ewan777** [comment]
The problem is, in the notification settings, the xfce volume daemon is enabled by default.
