### ISSUE TITLE
Cinnamon: the two "reverse scrolling direction" switches for mouse and touchpad should be linked

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/mint20-beta#108]
In Cinnamon, there are two "reverse scrolling direction" switches: one for the mouse and one for the touchpad. They function quite separately from each other, which makes little sense and is confusing.

The solution would be, to link those two switches to each other. So that a change in one, will automatically cause the same change in the other.

**Comment by xenopeek** [comment]
Cue an issue to make them separate again for people that do have a reason to have different settings. I think it would be better to make it more clear there are two settings; perhaps having them together in one tab or showing a note when changing one?

**Comment by voney** [comment]
100% disagree, OSX went down this path and it is one of the most irritating things to deal with if you're using a laptop with a dock (sometimes mouse, sometimes touchpad).

For example, the "normal" scroll direction for a mouse is rolling towards you scrolls down. On the other hand, touchpads originally had a similar UX where pulling your finger(s) towards you would scroll down, the advent of touchscreen devices and the default to "natural scroll" decisions by many manufacturers have changed this so it's now reversed from the original default (often called natural scrolling). 

If you were to link these two settings how would you decide what the default "not inverted" position should be? And how do you accommodate people who want to flip their touchpad direction (very common) without flipping their mouse scroll direction (very rare)?
