### ISSUE TITLE
Latest update of mintstick (USB Image Writer ans USB Stick Formatter) do not launch when clicked

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20-beta#109]
I installed the latest update of mintstick in less than 24 hours and the the two applications which are USB image writer and USB stick formatter fail to launch and nothing else happens when they are clicked from the start menu. The mintstick package that came with the Linux Mint 20 beta worked flawlessly but after the package was updated, they fail to launch when clicked
The only log entry that is logged every time I attempt to launch either or both applications of mintstick is:
`g_file_info_get_attribute_boolean: assertion 'G_IS_FILE_INFO (info)' failed`

**Comment by clefebvre** [comment]
Thanks I can reproduce it.

**Comment by xenopeek** [comment]
Appears to be caused by https://github.com/linuxmint/mintstick/commit/7ce2ac9d9528546e455bb21fd936438b8af39999.

When launched from terminal with `mintstick -m iso` or `mintstick -m format` the output is:
```
Traceback (most recent call last):
  File "/usr/lib/mintstick/mintstick.py", line 22, in <module>
    gi.require_version('Unity', '7.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Unity not available
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 144, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_mintstick_mintstick.py.999.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/mintstick/mintstick.py", line 22, in <module>
    gi.require_version('Unity', '7.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Unity not available
```

**Comment by clefebvre** [comment]
Fixed.

**Comment by ghost** [comment]
@clefebvre Thanks for the fix, they can launch now
