### ISSUE TITLE
Wildcard not working with the apt command

### ISSUE THREAD

**Issue by corefx** [linuxmint/mint20-beta#110]
root@linux:~# apt purge transmission-*
Luetaan pakettiluetteloita... Valmis
Muodostetaan riippuvuussuhteiden puu       
Luetaan tilatiedot... Valmis        
E: Pakettia transmission-* ei löydy

It says: "Package was not found" but transmission was installed.
apt-get purge transmission-* or apt-get remove transmission-* works.

Linux Mint 20 Cinnamon Beta 64 bit

**Comment by xenopeek** [comment]
Duplicate of #34
