### ISSUE TITLE
Fractional scaling issue with proprietary Nvidia drivers

### ISSUE THREAD

**Issue by malj** [linuxmint/mint20-beta#112]
https://github.com/linuxmint/cinnamon/issues/9369

**Comment by mtwebster** [comment]
Please check out this comment:
https://github.com/linuxmint/cinnamon-control-center/pull/238#issuecomment-646734935

Any feedback is appreciated,
Thanks

**Comment by malj** [comment]
The display menu changed after installing the [files](https://github.com/linuxmint/cinnamon-control-center/pull/238#issuecomment-646734935), but the problem is still present. Sorry for the bad picture, I had to take a photo of the screen because the screenshoot tool can't display the bottom and right bars.

![DC2BD976-2D63-4539-B722-BF5DCDF6070D](https://user-images.githubusercontent.com/8290012/85166924-4f008b00-b268-11ea-9b80-e0aa44969db3.JPG)

**Comment by mtwebster** [comment]
If you run:
```
xrandr --output eDP-1-1 --scale 1.25x1.25
```
Does the same thing occur?

edit: using scale 1x1 with the same command will restore it.

**Comment by malj** [comment]
Yes, but reversed, as per my original bug report in the Cinnamon repo:

- setting scale to `1.25x1.25` is the equivalent of choosing zoom level 75% in the display settings, i.e. the viewport overflows the screen
- setting scale to `0.75x0.75` produces the same problem as choosing zoom level 125% in the display settings

It seems that the viewport itself is being resized, instead of the content.

**Comment by mtwebster** [comment]
Ok sorry - I mainly wanted to compare our behavior against the 'reference' implementation of this, and it looks like the behavior is pretty much the same.  I confirm it also on a laptop in nvidia mode (prime).

Yet using the same drivers with another machine and different card, it works fine.

**Comment by malj** [comment]
Np, glad to help. I linked a similar [issue](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1870736) on Ubuntu 20.04 in the original report, I'm not sure if it has anything to with this, but it seems that Nvidia drivers are the underlying cause, as usual. Noveau works fine.

**Comment by clefebvre** [comment]
Hi,

This is upstream from us unfortunately and a limitation between xrandr and the GPU driver. What we'll do is make it clearer fractional scaling is ON and advertise it as an experimental feature with limitations.

**Comment by malj** [comment]
Thanks for the info, that's what I feared. This is my last Nvidia GPU for sure, after all the issues they've been causing with display servers on Linux for years.
