### ISSUE TITLE
Mint Welcome > First steps > Install Codecs fails

### ISSUE THREAD

**Issue by Webtest7** [linuxmint/mint20-beta#113]
Linux Mint 20 Mate 64-bit Beta "Welcome" "First Steps" page ...
Observation:  install of "Multimedia Codes" fails with a popup when the button is clicked.

Multimedia Codecs
Additional multimedia codecs are required ... Click the button below to install them:

E:The repository 'cdrom://Linux Mint 20 _Ulyana_ - Release amd64 20200610 focal Release' does not have a Release file.

![Screenshot-2020-06-18-LoadCodecFail](https://user-images.githubusercontent.com/37939718/85045498-07d9a380-b15d-11ea-8e7f-b47a4cb3fe36.png)

System: linuxmint-20-mate-64bit-beta.iso   LiveMedia system on locked USB thumbdrive.  Internet connection is active and working fine.

**Comment by clefebvre** [comment]
Thanks, that's a known issue, already on trello.
