### ISSUE TITLE
Transmission not translated in French in menu

### ISSUE THREAD

**Issue by enigma131** [linuxmint/mint20-beta#114]
I've finally setup French locale on usb stick, so i can test more translations ...
See picture under:
![Transmission](https://user-images.githubusercontent.com/31815445/85050962-68c9a180-b186-11ea-8822-c371da742c10.png)
Should be "Téléchargement ou partage de fichiers via BitTorrent"

**Comment by xenopeek** [comment]
That text comes from the line `Comment=Download and share files over BitTorrent` in the file `/usr/share/applications/transmission-gtk.desktop` in the package `transmission-gtk` from the focal repository. It does not come with translations for the Comment field. This is an upstream issue.
