### ISSUE TITLE
Strange section of text for system theme parameters , french locale

### ISSUE THREAD

**Issue by enigma131** [linuxmint/mint20-beta#115]
Open system parameters, go to theme, then tab paramètres
![Theme parameters](https://user-images.githubusercontent.com/31815445/85052399-5badb200-b188-11ea-979a-d7af78f1bffe.png)
See text "Lorem ipsum etc" not translated

**Comment by xenopeek** [comment]
[Lorem Ipsum](https://fr.wikipedia.org/wiki/Lorem_ipsum) is dummy text without meaning, used here only to let the user test the scrollbar settings.

**Comment by enigma131** [comment]
OK. Could perhaps put text in english , and put as text "this is a test area ...."
