### ISSUE TITLE
Calculator isen't translated at all in prefered applications

### ISSUE THREAD

**Issue by enigma131** [linuxmint/mint20-beta#116]
See bottom line at right should be "Calculatrice" too as in the menu is ok
![calculatrice](https://user-images.githubusercontent.com/31815445/85053088-8a785800-b189-11ea-8746-ae109dba4fb3.png)

**Comment by xenopeek** [comment]
That text comes from the line `Name=Calculator` in the file `/usr/share/applications/org.gnome.Calculator.desktop` in the package `gnome-calculator` from the focal repository. It does not come with translations for the Name field, which the .desktop files of the programs in your screenshot that are named in French do. This is an upstream issue.
