### ISSUE TITLE
[enhancement] Download section of Applets not translated

### ISSUE THREAD

**Issue by enigma131** [linuxmint/mint20-beta#117]
![applets](https://user-images.githubusercontent.com/31815445/85056091-24420400-b18e-11ea-8f59-5ca2e4954a78.png)
But setting tab is (translated)..
![gérer](https://user-images.githubusercontent.com/31815445/85056250-6cf9bd00-b18e-11ea-9eb5-b0f4d39242b9.png)

**Comment by NikoKrause** [comment]
It always has been this way. The translations files are stored within the applet and only get installed, when you download the applet.

**Comment by enigma131** [comment]
Yes, same in 19.3. I understand the technical behind... To be less confuse, I change the title. Could be confusing for non English speaking people , text could not be selected to put in a translator.
