### ISSUE TITLE
Why command-not-found is missing?

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mint20-beta#119]
Hi,

Why command-not-found is missing? It was coming by default in previous versions. if it is caused by the following error, https://bugs.launchpad.net/ubuntu/+source/command-not-found/+bug/1871670
I solved this problem in a basic way and packed it. You can try it if you want. link removed.

**Comment by xenopeek** [comment]
It's already on Trello; found during QA and will be fixed after stable.
