### ISSUE TITLE
Grub: Unable to differentiate between GRUB menu options for MATE and CINNAMON 

### ISSUE THREAD

**Issue by Peter-Nesbitt** [linuxmint/mint20-beta#121]
I installed LM20 Cinnamon, Mate, and Xfce on an old MacBook Pro. Installation and partitioning went fine, but I just followed the prompts and accepted most of the recommended settings along the way. When I start my computer the GRUB menu shows the following:

**Linux Mint 20 Xfce
Advanced options for Linux Mint 20 Xfce

Linux Mint 20 Ulyana (20) (on /dev/sda2)
Advanced options for Linux Mint 20 Ulyana (20) (on /dev/sda2)

Linux Mint 20 Ulyana (20) (on /dev/sda3)
Advanced options for Linux Mint 20 Ulyana (20) (on /dev/sda3)**

The first line is obviously Xfce, but looking at the menu, the remaining options do not indicate which one is Cinnamon or Mate. Through a couple of restarts I determined that the 2nd option is Mate and the 3rd option is Cinnamon.

Is it possible to change the menu names on the Grub(?) menu, or is this by design? Bug maybe? I was unable to find an answer online or at the Linux Mint forum.

I performed installations twice on a MacBook Pro with the same results and had the same results when installing all three versions on a Dell Inspiron desktop. As a side note, when loading from a live USB the desktop icon to install does not differentiate between versions either, as it simply states "Install Linux Mint".

I would expect that the GRUB menu options would indicate which version of Linux Mint is associated with each particular version that is installed.

Any thoughts on this?

Thanks,

Peter

**Comment by xenopeek** [comment]
Is my assumption correct that you installed Linux Mint 20 Xfce first on this system, installing the other 2 editions after it? Or in which order did you install these 3?

**Comment by Peter-Nesbitt** [comment]
No, I actually installed Cinnamon, Mate, and Xfce in this order.

**Comment by NikoKrause** [comment]
I'm curious, why you installed all 3 editions. As alternative you can install the Mate/Xfce/Cinnamon desktop environment on top of another one and just switch between the DEs in the login sreen. Would save a lot of disk space.

**Comment by clefebvre** [comment]
Hi Peter,

That's os-prober generating these, whereas the first item is generated by 10_linux in update_grub. We modify the title in 10_linux because it's important and affects almost everybody, but I don't think we'll do the same with os-prober.. it reads generic info from lsb afaik and this is a very niche case.

**Comment by Peter-Nesbitt** [comment]
Niko,



Thanks for your response.



I am a new Linux user and have been exploring and learning about Linux and various distributions during the lockdown. I installed all three versions just as an an exercise to see what would happen and to to possibly help with finding any bugs associated with my level of use.



I was not aware that I could install the DEs "on top of another one". In a Debian installation a few weeks back, I noticed something similar to what you describe and have been able to select different desktops at my login prompt. It looked like something unique to that particular distrobution.



Thanks for the tip... I will research this and see if I can learn how to do this with Linux Mint. Any tips or links would be appreciated!



Peter


On June 18, 2020 at 10:43 PM, NikoKrause <notifications@github.com> wrote:






I'm curious, why you installed all 3 editions. As alternative you can install the Mate/Xfce/Cinnamon desktop environment on top of another one and just switch between the DEs in the login sreen. Would save a lot of disk space.

**Comment by Peter-Nesbitt** [comment]
Clement,



Thanks for the response. Niko Krause emailed me this morning to say that there is a way to install DEs on top of each other instead of installing each version of LM separately as I have done. Gonna try to figure that out today.



Thanks for all that you do!



Peter


On June 19, 2020 at 3:14 AM, Clement Lefebvre <notifications@github.com> wrote:






Hi Peter,

That's os-prober generating these, whereas the first item is generated by 10_linux in update_grub. We modify the title in 10_linux because it's important and affects almost everybody, but I don't think we'll do the same with os-prober.. it reads generic info from lsb afaik and this is a very niche case.

**Comment by NikoKrause** [comment]
Here's a link, which describes it:

https://www.maketecheasier.com/install-mate-linux-mint/

It's pretty easy actually.
