### ISSUE TITLE
XFCE: Hover text with "Notification Area" plug-in displays below the panel bar.

### ISSUE THREAD

**Issue by Peter-Nesbitt** [linuxmint/mint20-beta#123]
After adding the "Notification Area" plug-in to my panel while using LM20 Xfce and increasing the pixel size via "Measurements > Row size for my old eyes, I noticed that the icon "comments" that pop-up while hovering now display below the panel bar and off of the screen. Not a big deal of course, but they are not visible.

Several other plug-ins display their respective comments above the plug-in with no problem.

A Row size of "30" was the magic number that made these comments disappear from my MacBook, while "50" was the the tipping point on my Dell but varied with each icon in the "Notification Area" plug-in.

Let me know if you need or want an additional data or reports for this one.

Peter

**Comment by mtwebster** [comment]
This is a known issue in gtk:
https://gitlab.gnome.org/GNOME/gtk/-/issues/2784

I didn't think xfce was affected though, I couldn't reproduce the issue when I checked.
