### ISSUE TITLE
synaptic PM  missing quick filter icon

### ISSUE THREAD

**Issue by STEPHEN-GOLDBOROUGH** [linuxmint/mint20-beta#124]
_Steps  to reproduce_

Open synaptic package manager in LM20  Xfce 
quick filter icon is missing from ribbon panel

_Workaround_
**successful**

(source askubuntu - Ubunhtu 16.19 had the problem

sudo apt-get install apt-xapian-index
sudo update-apt-xapian-index -vf

**Comment by STEPHEN-GOLDBOROUGH** [comment]
_Note_

in the .deb package apt-xapian-index is only listed as a recommend, not a dependency

**Comment by Pjotr123** [comment]
Sorry, but I disagree very much with the wish to bring this garbage back in the default installation. The Quick filter is, and has always been, horribly bad. It gives much less results than the ordinary Search button. Thank heaven that apt-xapian-index is no longer in the default Mint installation....

**Comment by STEPHEN-GOLDBOROUGH** [comment]
A [filter] is  a different beast to [search] . You can filter on  say, python, then find it in different categories on the left one after the other without rekeying the query. 

Breaking user functionality should, I guess, be a no no in linux.

**Comment by xenopeek** [comment]
apt-xapian-index is an optional component (suggests dependency) for Synaptic Package Manager and can be installed by those that want it as you've documented.
