### ISSUE TITLE
is there always grub menu show on every boot time of linux mint 20 ?

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20-beta#125]
I dont like grub menu always show on boot menu , if this feature is eneable by default in linux mint 20 then please tell me how to change the settings

**Comment by xenopeek** [comment]
This is reverted for the final release; it will only show Grub when you have multiple OSes installed. The User Guide details how to enable it if you only have Linux Mint installed and want the Grub menu always shown: https://linuxmint-user-guide.readthedocs.io/en/latest/grub.html
