### ISSUE TITLE
Can't install pip3 in Cinnamon 20

### ISSUE THREAD

**Issue by Hairybiker** [linuxmint/mint20-beta#127]
Pip3 or python-pip3 have no available downloads

apt install python-pip3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-pip3

apt install pip3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package pip3

It should be in the ubuntu universe repo but it isn't found

**Comment by xenopeek** [comment]
It's `python3-pip`: https://packages.ubuntu.com/focal/python3-pip
