### ISSUE TITLE
Some errors during packages installation

### ISSUE THREAD

**Issue by thegreatyellow67** [linuxmint/mint20-beta#129]
I would like to point out a couple of errors that I've found installing some packages from the repositories.

For example:

Preparing to unpack .../bleachbit_3.9.0-1_all.deb ...
Unpacking bleachbit (3.9.0-1) ...
Setting up bleachbit (3.9.0-1) ...
**/usr/share/bleachbit/bleachbit/__init__.py:260: SyntaxWarning: "is not" with a literal. Did you mean "!="?**
  if msgctxt is not None and msgctxt is not "":
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24+linuxmint1) ...

or:
Setting up python3-pycryptodome (3.6.1-2build4) ...
**/usr/lib/python3/dist-packages/Cryptodome/SelfTest/Random/test_random.py:103: SyntaxWarning: "is" with a literal. Did you mean "=="?**

[term.log](https://github.com/linuxmint/mint20-beta/files/4804734/term.log)

I've attached the complete log file relating to the installation of the apt packages.
Thanks.

**Comment by clefebvre** [comment]
they're just warning, also it's upstream from us: https://github.com/bleachbit/bleachbit/issues/902

**Comment by thegreatyellow67** [comment]
Ok, thanks.
