### ISSUE TITLE
Cursor/mouse pointer stutters in hidpi mode

### ISSUE THREAD

**Issue by hammadimir** [linuxmint/mint20-beta#13]
My laptop is HP Elitebook 840 G1. Display is 14" 1920*1080. I don't have any issues when hidpi is turned off. Everything is fine. However when I set on the hidpi in display settings (though not necessar) , the cursor starts to stutter and becomes too slow. I need to increase the pointer sensitivity and acceleration. Cursor becomes fast with stuttering.

**Comment by clefebvre** [comment]
Are you using fractional scaling? Can you take a screenshot of your display settings and the output of inxi -Gxx?

**Comment by hammadimir** [comment]
No I wasn't using fractional scaling. Actually, the issue seems to be gone automatically. I don't know how. So I think its okay. Thanks.
