### ISSUE TITLE
linux mint 20 hdd 100%

### ISSUE THREAD

**Issue by felipe13yt** [linuxmint/mint20-beta#133]
hello my linux mint is using 100% hd
I'm using linux mint 20 beta latest version

**Comment by LinuxOnTheDesktop** [comment]
I am not a developer but I know you will need to give much more information, including at least the following.

- Does the 100% usage occur immediately after installation?
- Have you verified that the usage is 100%, i.e. checked in more than one way? Can you provide a relevant screenshot or relevant terminal output?
- 100% usage of what size hard drive or partition?
- Which flavour of Mint (Cinnamon, Mate or XFCE)?
