### ISSUE TITLE
SNI: HTML tooltip from qBittorrent

### ISSUE THREAD

**Issue by Docmine17** [linuxmint/mint20-beta#137]
The Qbittorrent indicator is not displaying the popup correctly, only a long code is displayed when the cursor* is over the icon.

  When installing the version of the repositories and that of Flathub, that of Flathub is not displayed in the indicator, and that of the repositories is not displayed in the menus.

To reproduce, just install the two versions of Qbittorrent (repositories and Flathub) and rest the mouse on the Qbittorrent indicators, and in the menus you can see that something is missing.

I tested version 20 beta installed on a VM (Gnome Boxes)

[Gtranslate]

![Bug20](https://user-images.githubusercontent.com/67164552/85166279-6d9d5c80-b23d-11ea-918a-4fc93e266628.png)

below Linux Mint 19.3
![Captura de tela de 2020-06-19 15-11-17](https://user-images.githubusercontent.com/67164552/85167847-de457880-b23f-11ea-9e86-3266a40e24d4.png)

below Linux Mint 20
![Captura de tela de 2020-06-19 15-10-52](https://user-images.githubusercontent.com/67164552/85167859-e6051d00-b23f-11ea-87b0-8853f92da5ce.png)

[code]
System:    Kernel: 5.4.0-37-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.4 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Kvm System: QEMU product: Standard PC (i440FX + PIIX, 1996) v: pc-i440fx-4.1 
           serial: <filter> Chassis: type: 1 v: pc-i440fx-4.1 serial: <filter> 
           Mobo: N/A model: N/A serial: N/A BIOS: SeaBIOS 
           v: rel-1.12.1-0-ga5cab58e9a3f-prebuilt.qemu.org date: 04/01/2014 
CPU:       Topology: 6-Core model: AMD FX-6100 bits: 64 type: MCP arch: Bulldozer rev: 2 
           L2 cache: 512 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 39778 
           Speed: 3315 MHz min/max: N/A Core speeds (MHz): 1: 3315 2: 3315 3: 3315 4: 3315 5: 3315 
           6: 3315 
Graphics:  Device-1: Red Hat QXL paravirtual graphic card driver: qxl v: kernel bus ID: 00:02.0 
           chip ID: 1b36:0100 
           Display: x11 server: X.Org 1.20.8 driver: none unloaded: fbdev,modesetting,vesa 
           resolution: 1024x768~60Hz 
           OpenGL: renderer: llvmpipe (LLVM 9.0.1 128 bits) v: 3.3 Mesa 20.0.4 compat-v: 3.1 
           direct render: Yes 
Audio:     Device-1: Intel 82801FB/FBM/FR/FW/FRW High Definition Audio 
           vendor: Red Hat QEMU Virtual Machine driver: snd_hda_intel v: kernel bus ID: 00:04.0 
           chip ID: 8086:2668 
           Sound Server: ALSA v: k5.4.0-37-generic 
Network:   Device-1: Intel 82371AB/EB/MB PIIX4 ACPI vendor: Red Hat Qemu virtual machine 
           type: network bridge driver: piix4_smbus v: N/A port: c1e0 bus ID: 00:01.3 
           chip ID: 8086:7113 
           Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter 
           vendor: Red Hat QEMU Virtual Machine driver: 8139cp v: 1.3 port: c000 bus ID: 00:03.0 
           chip ID: 10ec:8139 
           IF: ens3 state: up speed: 100 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 20.00 GiB used: 9.54 GiB (47.7%) 
           ID-1: /dev/sda vendor: QEMU model: HARDDISK size: 20.00 GiB speed: <unknown> 
           serial: <filter> 
Partition: ID-1: / size: 19.07 GiB used: 9.54 GiB (50.0%) fs: ext4 dev: /dev/sda5 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 6 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 2 rev: 1.1 chip ID: 1d6b:0001 
Sensors:   Message: No sensors data was found. Is sensors configured? 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com ulyana main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 204 Uptime: 1m Memory: 1.94 GiB used: 705.7 MiB (35.5%) Init: systemd v: 245 
           Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client inxi: 3.0.38 
[/code]

**Comment by mtwebster** [comment]
This is an issue with qbittorrent.  They should not be using html here.

For now we won't be displaying this tooltip (it will be replaced with just the app name).  If this isn't desirable, there will be a way to restore the old tray icon (and tooltip).

qbittorrent issue:  See: https://github.com/qbittorrent/qBittorrent/issues/13035
commit to disable the html tooltip: https://github.com/linuxmint/xapps/commit/40a01f53fa149eda5f192ec54722e55250bbfb2d
commit to allow forcing qt (among other) applications to use the old-style tray icon: https://github.com/linuxmint/xapps/commit/adee25282a898fa11fe93b518993e10fac993a05
