### ISSUE TITLE
Cinnamon - Nemo has a delay in displaying picture thumbnail images

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/mint20-beta#14]
Symptom: When returning to a previous directory where an image file has already had a thumbnail generated and cached, there is a delay in displaying the thumbnail image in Nemo.  In Mint 19.3 on the same hardware, it is instantaneous.
This has been seen on several computers so I am not sure it is a graphics kernel/driver issue.
I am logging this because this seems to be a regression.

How to reproduce.  Save a screen shot to ~/Downloads.  Go to ~/Downloads to view/open the file in Nemo.  Navigate away.  Navigate back to ~/Downloads and observe the issue.
Hardware is an i7-4790 with GeForce GTX 1050 Ti just for reference.

**Comment by pasch256** [comment]
yeap i think have to be the reading of the cache... in my vm.. take a fraction of the seg. show the thumnail. in 19.3, is more faster, much much faster.

**Comment by mtwebster** [comment]
Hi, check out https://www.linuxmint.com/rel_ulyana_cinnamon_whatsnew.php under Cinnamon 4.6 for more of an explanation.  This was deliberately done to improve directory loading performance.

Some further details:
https://github.com/linuxmint/nemo/commit/bb049a4d89535202b4d525d1db27421d31c0af22
https://github.com/linuxmint/nemo/commit/4386080667571f1acd9c442fcd79658eee41b93f

**Comment by Acheron17** [comment]
But I shouldn't be seeing it in a top directory with only one file in the
directory.
Not on a system of that performance with a SSD drive.

**Comment by mtwebster** [comment]
Ah you might have a point, I'll do something to try improve this for less-populated folders.

**Comment by Acheron17** [comment]
Thank you kindly for at least taking another look at it.  When I first saw it, I thought there was something wrong with my graphics and tried it on other computers and different directory levels.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/07e18afeba5bd3df1773d65cca22b2e832aa01b1

This should take care of the issue.
