### ISSUE TITLE
Lenovo Ideapad L340-15IRH Gaming - Battery issue

### ISSUE THREAD

**Issue by HansBinBrabant** [linuxmint/mint20-beta#140]
Battery capacity issue within Linux Mint 19.2 and 19.3. Improved in 20 ?

In my Lenovo Ideapad L340-15IRH Gaming, 
with Linux Mint 19.2 and then 19.3 installed
My battery does not last even 2 hours.
Reading around on the internet, my perception is that it is caused by the video card management
NVidia and Intel are both on board. Normally I want to use the intel. Which will be good enough.
I believe the NVidia is always consuming power, even when it is not used.
"Linux Mint 20 will feature improved support for NVIDIA Optimus". I hope this one is good for me !

I hope this will be improved in Mint 20.
If I can test somehow, any improvements, please let me know. I will do !

Thanks in advance
Hans

**Comment by clefebvre** [comment]
I heard NVIDIA is powered all the time, even in on-demand mode. @mtwebster reported battery life didn't decrease for him in that mode, compared to the Intel mode. So in brief, I'm not really sure :)

Closing this as it's not a BETA blocker.
