### ISSUE TITLE
Lenovo Ideapad L340-15IRH Gaming - Keyboard issue with NumLock, home and end

### ISSUE THREAD

**Issue by HansBinBrabant** [linuxmint/mint20-beta#141]
Lenovo Ideapad L340-15IRH Gaming - Keyboard issue

In my Lenovo Ideapad L340-15IRH Gaming, 
with Linux Mint 19.2 and then 19.3 installed
and also 
In Linux Mint 20 Cinnamon Beta, running live from USB stick, 

Keyboard numlock on/off x Home and End key x text editing with CTRL ALT and SHIFT functions : mismatch 

What goes wrong ?
it is about using the keyboard for moving the cursor through any text, with using the 7/Home and 1/End function (on the right side numeric key area) for selecting text.
I have learned this functionality in the 90' on unix computers, and still use it. I do want it to work.
Example : Put the cursor at the end of a line of text. Do NumLock off. Press Shift and Home, to select the whole line. A 7 appears, while the whole line from end to the beginning (Home) should be selected.
Same thing with the cursor at the beginning (or anywhere in a line) of a line of text. Do NumLock off. Press Shift and End. A 1 appears. No selection to end of line made.

Another way of telling : With NumLock off, press Shift and a digit key, and that number shows up in de terminal. While numlock is off.

My alternative way of working :
Using Home and End on the left and right arrow key, by use of the Fn key : Shift Fn -> : tadaa line selected.

It happens on this laptop only. But in any linux of Mint (xface and Cinnamon, 19.x and 20 beta) and Linux MX, I have tested it in Linux on all kinds of text adding opportunities in Office writer, xed, geany, all the same. 
On this computer with windows 10 it works as expected.
On my desktop computer with Linux Mint 18.3 installed, it works as expected. As it always did on all other computers with windows and linux running ...          
On my businuss computer (windows 10 only) it works as expected.   

Before I will install Mint 20, I will run all updates by use of the Lenovo admin utility available in windows 10. Question about this : how to keep the uefi/bios up to date with the by the manufacturer provided updates, from within Linux only ?     

I hope this will be fixed in Mint 20.
If I can test some improvements, please let me know. I will do !

Thanks in advance
Hans

mint@mint:~$ inxi -Fzx
System:    Kernel: 5.4.0-26-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.3 
           Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: LENOVO product: 81LK v: IdeaPad L340-15IRH Gaming serial: <filter> 
           Mobo: LENOVO model: LNVNB161216 v: SDK0R32862 WIN serial: <filter> UEFI: LENOVO v: BGCN28WW date: 12/27/2019 
Battery:   ID-1: BAT0 charge: 18.2 Wh condition: 42.4/45.0 Wh (94%) model: Celxpert L18C3PF1 status: Charging 
CPU:       Topology: 6-Core model: Intel Core i7-9750H bits: 64 type: MT MCP arch: Kaby Lake rev: A L2 cache: 12.0 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 62399 
           Speed: 1300 MHz min/max: 800/2600 MHz Core speeds (MHz): 1: 1343 2: 1361 3: 1340 4: 1303 5: 1342 6: 1763 7: 1872 
           8: 1878 9: 1824 10: 1328 11: 1346 12: 2160 
Graphics:  Device-1: Intel UHD Graphics 630 vendor: Lenovo driver: i915 v: kernel bus ID: 00:02.0 
           Device-2: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] vendor: Lenovo driver: nouveau v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1600x900~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 20.0.4 direct render: Yes 
Audio:     Device-1: Intel Cannon Lake PCH cAVS vendor: Lenovo driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           Device-2: NVIDIA vendor: Lenovo driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k5.4.0-26-generic 
Network:   Device-1: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter vendor: Lenovo driver: ath10k_pci v: kernel 
           port: 4000 bus ID: 07:00.0 
           IF: wlp7s0 state: down mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Lenovo driver: r8169 v: kernel port: 3000 
           bus ID: 08:00.0 
           IF: enp8s0 state: down mac: <filter> 
           Device-3: Qualcomm Atheros type: USB driver: btusb bus ID: 1-14:5 
Drives:    Local Storage: total: 968.42 GiB used: 62.1 MiB (0.0%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: MZVLB1T0HALR-000L2 size: 953.87 GiB 
           ID-2: /dev/sda type: USB model: UFD 2.0 Silicon-Power16G size: 14.55 GiB 
Partition: ID-1: / size: 7.76 GiB used: 19.2 MiB (0.2%) fs: overlay source: ERR-102 
           ID-2: /var/log size: 12.45 GiB used: 42.9 MiB (0.3%) fs: ext4 dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 55.0 C mobo: N/A gpu: nouveau temp: 43 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 293 Uptime: 4m Memory: 15.52 GiB used: 859.1 MiB (5.4%) Init: systemd runlevel: 5 Compilers: gcc: 9.3.0 
           Shell: bash v: 5.0.16 inxi: 3.0.38

**Comment by clefebvre** [comment]
Hi @HansBinBrabant,

If this worked in 18.3 and not in 20, I'd suggest the following:

- Create an issue on https://github.com/linuxmint/linuxmint/issues
- Make sure the keyboard layout is exactly the same in both versions (same keyboard model, same layout, same variant, same options)
- Provide screenshots for both
- Provide a simple sequence of keys pressed for us to reproduce and explain exactly what happens and should happen. Don't hesitate to screenshot the text and text selection you mention.

I'll close this here as it's not new and not specific to Mint.
