### ISSUE TITLE
Nemo strange message for Android connected device

### ISSUE THREAD

**Issue by enigma131** [linuxmint/mint20-beta#142]
After connecting my Android device to the laptop and after accepting sharing on smartphone, i get strange message for  mounted device in Nemo screen (I'm still on live, all is updated except libreoffice and kernel, Cinnamon edition).
![android](https://user-images.githubusercontent.com/31815445/85196647-35dcf600-b2cb-11ea-8329-b0c104e47d60.png)

**Comment by aureoud-fr85** [comment]
This is duplicate of [https://github.com/linuxmint/mint20-beta/issues/111](https://github.com/linuxmint/mint20-beta/issues/111)

Regards,

**Comment by xenopeek** [comment]
Duplicate of #111

**Comment by enigma131** [comment]
Oops yes
