### ISSUE TITLE
xreader.thumbnailer fails to thumbnail files that it could thumbnail in Mint 19.x

### ISSUE THREAD

**Issue by smurphos** [linuxmint/mint20-beta#143]
Hi,

Filetype - cbr (Comic Book Rar) - sample file - https://example-files.online-convert.com/ebook/cbr/example.cbr

On Mint 19.x 
```
steve@steve-Inspiron-5580:/mnt/backup_drive/Downloads$ mimetype ./example.cbr
./example.cbr: application/x-cbr
```
This thumbnails fine in 19.3 - application/x-cbr is a supported mimetype in /usr/share/thumbnailers/xreader.thumbnailer

On Mint 20 with the same example file.
```
steve@steve-VirtualBox:~/Desktop$ mimetype ./example.cbr
./example.cbr: application/vnd.comicbook-rar
```
Doesn't thumbnail. Manually adding the latter mimetype to /usr/share/thumbnailers/xreader.thumbnailer resolves the issue. 

I guess there could be other mimetype changes between 19.x and 20 that could impact thumbnailing?

**Comment by clefebvre** [comment]
Fixed in upcoming xreader 2.6.3 (awaiting translations to be tagged).
