### ISSUE TITLE
cinnamon: Custom Keyboard Shortcut issue

### ISSUE THREAD

**Issue by rdlf4** [linuxmint/mint20-beta#144]
I wanted to replace gnome-screenshot with Flameshot, which works perfectly on Linux Mint 18 & 19. 
The problem here is that, when assigning the PrintScreen button to it, I'm warned that it it's currently in use by _Take a Screenshot_ (from System > Screenshots and Recording). I then proceed by clicking on Yes from the prompt pop up, which assigns the PrtSc button to the command `flameshot gui`, which results in nothing happening after the fact.
I then checked for conflicts, but _Take a Screenshot_ has its buttons unassigned. Nowhere to go from here.

**Comment by xenopeek** [comment]
I can reproduce this but the custom keyboard shortcut starts working after restarting Cinnamon (Alt+F2 → r → Enter).

It seems to be a problem with changes to keyboard shortcuts not taking effect immediately after making them, requiring a session restart?

**Comment by rdlf4** [comment]
Interesting. I even went the extra mile and, instead of restarting Cinnamon, I did my computer.
And somehow this bug was still there.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/4531ff5e9f967ce9051124519b9a9daca12e21ea

I messed up the link in the commit
