### ISSUE TITLE
Mate Compiz Issues.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20-beta#145]
Mint 20 Mate Beta Issues:

Default app selections are poor.

Gimp should be installed by default. Period. Also it should be pre-configured to be in single window mode. And be in the favorites in the Mint menu.
Audacious is much lighter/better/faster than Rhythmbox which is bloated and slow. Should also be in the favorite menu.
OBS-studio is insanely popular and should be available in the repos without adding a custom PPA.
Qbittorrent is a lot better than transmission.
K3b is a lot better than brasero
Libre Office apps should be in the favorites list by default. Definitely the spreadsheet and word processor.
Ublock origin should be installed in firefox by default.
VLC should be installed by default. Period.
Aisle Riot should be installed by default, and in the mint menu favorites.

Software Manager Issues.

Tor Browser should be in the software manager.
Editors’ Picks could be a lot better. Gnome Maps, Sublime, PIA Manager, Calibre, and Shutter could definitely be replaced. My suggestions: 0 AD, higan, filezilla, audacity, blender, openshot, dolphin emulator
Curating some of the software manager store items to show more polished/popular titles at the top of the list would be good. Especially in the games list.

Compiz Issues.

No default compiz config. Lots to fix here:
Default to 4 desktops/viewports/workspaces (same as Marco or Cinnamon)
Enable OpenGL and Compositing
Enable MATE Compatibility
Enable Enhanced Zoom Desktop (should be Enhanced Desktop Zoom, ENGLISH!) (plus enable the mouse scroll wheel controls)
Enable Opacity, Brightness, Saturation
Enable Desktop Cube and Rotate Cube (and setup better defaults (zoom, speed, etc.)
Enable 3D Windows
Enable Firepaint and Window Decoration
Enable JPEG, PNG, SVG, and Text (Image Loading sub category)
Enable Mouse position polling
Enable Move Window, Resize Window, Snapping Windows, Grid

Mate/Theming Issues.

ALT+CTRL+T should open a terminal. Duh
Dark Themes are darker than the Darker Themes
Calculator is old and ugly. Let’s make a newer/prettier version.
No Darkest Theme (True black)
Have the color selection separate from the theme selection. Themes should be light, lighter, lightest (lightest being total white backgrounds, windows, etc.), and dark, darker, and darkest (darkest being totally black for menus, windows, etc.). Then the folder/icon default color selection can be a separate selection, and it should be a color wheel wherein you can pick ANY color (with a few good defaults available to click on directly).

See Mock Up:
https://ibb.co/jGZ4k60

Oh, and here's my video of the beta testing real time: https://youtu.be/GvR5yvahqOk

**Comment by clefebvre** [comment]
Thanks for the feedback.

**Comment by crhy** [comment]
So does that mean we'll have a better compiz default config at least?  Thank you!
