### ISSUE TITLE
Wi-Fi problem on Acer laptop

### ISSUE THREAD

**Issue by rodinf** [linuxmint/mint20-beta#146]
After about an hour of operation the wifi turns off, but the icon on the taskbar shows that the wifi is connected. When you click on the wifi icon, the system freezes for about a minute. Only the reboot helps.

Acer Swift 3 sf314-56

**Comment by clefebvre** [comment]
Can you reproduce the issue with nm-applet (remove the network applet from the panel and nm-applet will replace it).

**Comment by clefebvre** [comment]
When you say the system freeze, you can still move the mouse or not?
