### ISSUE TITLE
When Titlebar buttons set to left, some softwares still shows buttons on right

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20-beta#15]
In Disks, Welcome window, Software sources, Bluetooth..., titlebar buttons remain at right even when they are set to left :

![Capture du 2020-06-14 12-21-14](https://user-images.githubusercontent.com/3955499/84590762-8ff83a00-ae39-11ea-9dbf-6a26a02167d8.png)
(if buttons were at left, where to put the Bluetooth on/off button ?)

![Capture du 2020-06-14 12-15-12](https://user-images.githubusercontent.com/3955499/84590693-16f8e280-ae39-11ea-8655-0fbd606c6847.png)

It's an old bug and bug report was closed without beeing solved :o(
https://github.com/linuxmint/linuxmint/issues/179

**Comment by clefebvre** [comment]
Is this in MATE?

**Comment by InfoLibre** [comment]
Sorry. Yes, it's in MATE.

**Comment by mtwebster** [comment]
https://github.com/mate-desktop/mate-control-center/pull/574

**Comment by mtwebster** [comment]
Going to close this, patch submitted upstream.
