### ISSUE TITLE
mintreport process fires up

### ISSUE THREAD

**Issue by prateekamana** [linuxmint/mint20-beta#151]
And started using my cpu cores intensively, to 100%, why does the process take so much cpu and why did it run up out of the blue ?

**Comment by clefebvre** [comment]
It's supposed to run, it checks for issues in the background.

Why does it take 100% CPU though? That's not normal. Can you kill all `mintreport` and `mintreport-tray` processes and run mintreport from the command line?

`mintreport`

See if it takes 100% CPU then, and which test is taking a long time (the name of the test being run shows up in the command line).

**Comment by prateekamana** [comment]
When I killed mintreport it stopped taking so much CPU, I didn't immediately try running mintreport as it only happened twice. I just ran mintreport from the command line and it doesn't take as much cpu as it does when it automatically starts running.

**Comment by clefebvre** [comment]
OK, we'll need to know more to be able to fix anything. If you find out what mintreport is doing when it's 100% or a way to always reproduce the issue, open a new issue on the mintreport repository.

In the meantime, if you want a workaround, you can disable mintreport in the startup applications.
