### ISSUE TITLE
Installer presentation translation for Italian language have an error and need some improvements

### ISSUE THREAD

**Issue by bomdia** [linuxmint/mint20-beta#155]
I know is not a killer bug, but there is an error and some phrases aren't very good to read in italian language.
i'll start with the error, is located in the last page of the presentation and is the word "giuda" that is wrong the correct word is "guida" but all this sentence isn't very good in italian, i'll make this more like: "Fornita di una guida utente, e un sito dedicato alla community, tante piccole guide e forum attivi, ha anche varie chat e una delle comunità più dinamiche di internet."
i think that i never heard "camere di confabulazione" it taked me a moment to understand that was chatrooms originally.
another thing that in italy we don't use is rete sociale we use social network or social you use this words in the tab where you reccomend skype etc you can translate it from
"IRC o sulla tua rete sociale preferita." to "IRC o sul tuo Social preferito." and from "Discord e molte altre reti." to "Discord e molti altri Social Network."

**Comment by bomdia** [comment]
i've submitted the corrected translation on launchpad and reworked some other so that they are more fluent and correct while reading

**Comment by xenopeek** [comment]
Thanks for improving translation. For all Linux Mint projects translations will be update before the stable release.
