### ISSUE TITLE
Preferences > Display > Zoom Level weird behaviour with Nvidia

### ISSUE THREAD

**Issue by DarkOwl2** [linuxmint/mint20-beta#156]
Ryzen5 with GT710 graphics, LM20 Cinnamon installed via Compatibility Mode + Nvidia drivers (default Nouveau drivers don't work at all with GT710).

Zoom levels other than 100% (or at least those which work) do not apply scaling equally vertical and horizontal.  Horizontal is stretched more than vertical.  22

LM18.2 works fine on my hardware without any special drivers.  Why can't 20 do the same?

Zoom level 100%:

![91E211E4-8F84-41DF-8DA7-0D922EFCA64B](https://user-images.githubusercontent.com/67048140/85209843-082b9780-b333-11ea-9bb3-25531bda06c3.jpeg)

Zoom level 125%:

![3686EB33-8435-43AB-82DB-F91F749521E0](https://user-images.githubusercontent.com/67048140/85209850-209bb200-b333-11ea-98a0-f9b65989e701.jpeg)

Zoom level 150%:

![38FDD3D9-9B76-4572-9EF5-8D3040F14DD0](https://user-images.githubusercontent.com/67048140/85209881-6789a780-b333-11ea-93bf-1a473b1bafd8.jpeg)

Zoom level 175%:

![9EC4EC01-687C-4D8E-8BD5-D4B5EB880952](https://user-images.githubusercontent.com/67048140/85209952-0adabc80-b334-11ea-83c2-6d077a15f3e5.jpeg)

Zoom level 200%:

![93813490-B792-4A88-A9D8-4E6023CABB92](https://user-images.githubusercontent.com/67048140/85210009-7886e880-b334-11ea-93d3-55ce5c56b775.jpeg)

(Zoom levels 75% and 250% similar, only 100% works properly)

Zoom levels 220% (should that read 225%?) and 275% crash the display app:

![F35D200B-EABF-4359-BF51-B28EEBCD28FA](https://user-images.githubusercontent.com/67048140/85210045-c26fce80-b334-11ea-8c99-d39efb48d337.jpeg)

After that, nothing works until the display app is closed and restarted.

Can't find the HI-DPI setting (present in 18.2) anywhere - would much prefer to set HI-DPI and then fine-tune with zoom level.

**Comment by DarkOwl2** [comment]
Additional info:

Having scaled the background, it did not return to normal at 100% zoom (although the other desktop features did).  With an enlarged background, the desktop became scrollable.

**Comment by clefebvre** [comment]
Hi,

This is upstream from us unfortunately and a limitation between xrandr and the GPU driver. What we'll do is make it clearer fractional scaling is ON and advertise it as an experimental feature with limitations.

**Comment by DarkOwl2** [comment]
How does that solve my problem with a hi-dpi monitor?  200% is not a fractional scaling, and doesn't work properly on my hardware.

**Comment by clefebvre** [comment]
you're zooming 2x with a 1x ui scale... the upcoming version of cinnamon-control-center will make it clearer you're using upscaling.

**Comment by DarkOwl2** [comment]
In 18.2, Preferences > General > Desktop scaling = Auto | Normal | Double.  I can't find the same thing in 20, the only alternative appears to be 2x zoom.

Turning on Hi-DPI Support in the login window settings gets the right effect for the login screen, but not once logged in.

**Comment by DarkOwl2** [comment]
OK, found it in Preferences > Display > Layout > Base Interface scale... but it doesn't work on my hardware.  I'll raise another issue.
