### ISSUE TITLE
No audio in Cinnamon or MATE with headphone/external speaker - Dell Inspiron laptop

### ISSUE THREAD

**Issue by ARaj64** [linuxmint/mint20-beta#157]
Clem, first of all I'm a MATE user. Have always been.
Okay Clem, since you requested me to test with Cinnamon...

Same result. I had to key in the command "alsactl restore".
The Ubuntu MATE 20.04 live disk has the same problem.
At times both internal speaker and the external speaker played audio at the same time.
Why do I have to enter "alsactl restore" to get audio working?

Audio works fine with Linux Mint MATE/Cinnamon 19.3.
So what gives? Is this a kernal or driver issue?

**Comment by xenopeek** [comment]
This is a follow up on previous issue reported for MATE #46

**Comment by clefebvre** [comment]
@ARaj64 yes, that's why I asked to test Cinnamon. I wanted to make sure it wasn't specific to a given DE.

So now we know it's lower than that. It could be a kernel issue, or a pulseaudio issue. Either way it's upstream from us.

**Comment by clefebvre** [comment]
I'd suggest you use `lspci` to precisely identify your audio chipset, and then look for bug reports on Launchpad related to it. If you can't find any, open a new one. You might also find workarounds.
