### ISSUE TITLE
Xfce - Switching primary monitor does not move desktop icons and Xfce Panel

### ISSUE THREAD

**Issue by lupusmagist** [linuxmint/mint20-beta#158]
Having two monitors, switching primary display between the two in Setting Manager=> Display does not move Desktop icons or Xfce Panel to primary display. Reboot/reload with logout has no effect.

I would expect the Panel and desktop Icons to move to the primary display selected. 

Manually moving items to primary display works as expected and persists after reboot.

**Comment by clefebvre** [comment]
Right-click the desktop, settings, icons, you can ask Xfce to display icons on the primary monitor.
