### ISSUE TITLE
No sound enabled when booting Mint 20 in VMWare workstation

### ISSUE THREAD

**Issue by KodyScotch** [linuxmint/mint20-beta#16]
When booting Mint 20 beta in VMWare WS (15.5.6) the messages from VMWare always appears:
"The default sound device cannot be opened
Device ID that is been used is out of range"
The sound device is then not enabled, after manually enabling the device in the VM settings the sound works fine.
I found no related message in the Mint syslog.

**Comment by charles-vomacka** [comment]
I just installed to VMWare Player 15.5.6 and did not experience this problem. I have experienced this problem in the past and it was related to the Host OS's (Windows) Sound Devices. To correct the problem I would enable the "Stereo Mix" recording device.

**Comment by KodyScotch** [comment]
Thanks, that did the trick!
