### ISSUE TITLE
Bluetooth query

### ISSUE THREAD

**Issue by brianmckillop** [linuxmint/mint20-beta#162]
I use a Toshiba Satellite C50. On opening bluetooth, no bluetooth adapter is found.

**Comment by clefebvre** [comment]
It could be a hardware issue, a kernel issue, a driver issue, a gnome-bluetooth issue, or a blueberry issue. If you find out it's a blueberry issue, given enough information, we'll be able to fix it. Open a new issue if you get to this point.

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/

**Comment by brianmckillop** [comment]
For your info, I am using LM 19 and have experienced no issues with Bluetooth.

**Comment by NikoKrause** [comment]
Then it's probably not a hardware issue.
It still can be a kernel issue, a driver issue, a gnome-bluetooth issue, or a blueberry issue.

Try to install the same kernel, which you had in Mint 19 to figure out if it's a kernel issue or not.

**Comment by brianmckillop** [comment]
I wonder if it's a driver issue? When I installed LM20 in Virtualbox, on startup I got a notification of a driver issue. I ran the driver manager as requested, but it only said that I had no proprietary drivers installed. Any thoughts?
