### ISSUE TITLE
SNI: QDBusTrayIcon encountered a D-Bus error

### ISSUE THREAD

**Issue by AegisPrime** [linuxmint/mint20-beta#164]
When opening KeePassX (or XC) with system tray icons enabled, the program takes a long time to open and reports this in the shell:

**qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: yes
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.NoReply", "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")**

This doesn't happen in Mint 19.3

**Comment by clefebvre** [comment]
Cool, this looks like the teamviewer issue, but with more info.

**Comment by clefebvre** [comment]
Possible fix https://github.com/linuxmint/xapps/commit/624992e975e5048d95e11cd113b373a846212eb1

**Comment by mtwebster** [comment]
This is a known issue with keypassxc - I've added details of the problem and how to fix on an existing bug report:
https://github.com/keepassxreboot/keepassxc/issues/4768

In the mean time, we're adding a way for the user to force qt apps (like keypassxc) to use the old-style tray icon and avoid this problem:
https://github.com/linuxmint/xapps/commit/adee25282a898fa11fe93b518993e10fac993a05
