### ISSUE TITLE
Showing SMART data at the beginning of the installation

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20-beta#166]
Sometimes, we install Linux Mint and at the end of the operation, we look the SMART data in Disks, to be sure that all is OK. But then, it's too late if there are bad sectors, we made the installation for nothing :

![Secteur_endommage_1](https://user-images.githubusercontent.com/3955499/85230375-d62c3b00-b3ef-11ea-968b-2bf420a2a8f3.png)

Could you show the SMART data, like in Disks, at the beginning of the installation, in GParted, for each device ?

**Comment by clefebvre** [comment]
Sorry @InfoLibre we're in BETA rush, we can't take feature requests at the moment.

**Comment by InfoLibre** [comment]
Sorry. I made a report at https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/373932
I don't know if it's the right place...
