### ISSUE TITLE
GRUB menu disappears after updating.

### ISSUE THREAD

**Issue by alan7000** [linuxmint/mint20-beta#168]
In Linux Mint 20, the grub menu always appears.

Problem : 
When I execute the "update-grub" command.
Grub no longer appears at boot time.

Solution:
I think I found the problem. In the file "/etc/default/grub", there is the variable "GRUB_TIMEOUT_STYLE" which is equal to "hidden" and the variable "GRUB_TIMEOUT" which is equal to 0. Because of this small error, the slightest update of grub will cause it to no longer appear at startup.

**Comment by xenopeek** [comment]
Grub menu always showing was reverted during beta. It will as before only be shown when multiple OSes are installed or you manually configure it to always show. The User Guide covers how to do that configuration if you have a system with only Linux Mint 20 on it and you want the Grub menu to always show: https://linuxmint-user-guide.readthedocs.io/en/latest/grub.html
