### ISSUE TITLE
Mint 20 - Cinnamon - Kaffeine double warning

### ISSUE THREAD

**Issue by Mr-Jiggs** [linuxmint/mint20-beta#169]
I use Kaffeine version 2.0.18 and when I close it I get a warning that I have scheduled recordings. When I respond "Yes" (I do want to close it) the warning dialog pops up a second time. Click "Yes" a second time and the app closes. The warning only appears once with Mint 19.3 Cinnamon.
Not a real problem, but I thought I'd let you know…

**Comment by clefebvre** [comment]
Thanks @Mr-Jiggs. Unless it's specific to one of our DEs, this should be reported to Kaffeine directly.
