### ISSUE TITLE
Update manager crashes

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20-beta#17]
Update manager crashes if it is launched immediately after booting Linux Mint MATE 20.

https://github.com/linuxmint/mintupdate/issues/604

**Comment by xenopeek** [comment]
As you know mintupdate starts 20s after log in and kills any previously running mintupdate process to avoid conflict. A workaround if you want to start mintupdate earlier is to disable Update Manager in Startup Applications. This isn't an issue specific to the beta.

**Comment by InfoLibre** [comment]
This bug couldn't be solved by not starting mintupdate 20s after login but 10 minutes after login, as set here ?

![Capture du 2020-06-14 15-42-52](https://user-images.githubusercontent.com/3955499/84594978-cfcd1a80-ae55-11ea-9111-d1dad46a5eba.png)

**Comment by xenopeek** [comment]
As explained, it's how mintupdate avoids conflict when it's started and there's already a running mintupdate process.

Your screenshot show configuration for when Update Manager will do things when it is running, not for when Update Manager will be started. For that look for Startup Applications in your menu (not in Update Manager). I don't know the French name for Startup Applications but it is the program where you can configure which programs should be started after you log in.

**Comment by InfoLibre** [comment]
But isn't it really possible to avoid this crash ? This bug is old and I don't have it in another distributions.

**Comment by xenopeek** [comment]
It's not a bug and if you want to start Update Manager manually within 20 seconds after logging in, I've explained how to do that: disable Update Manager starting automatically in Startup Applications in your menu.

**Comment by InfoLibre** [comment]
Disabling Update Manager starting automatically in Startup Applications should indeed be done by default. Because :
- When you start your computer, you use it immediately and don't want it to be slow.
- If the Update Manager is set to start after 10 minutes, why starting it at boot ?

**Comment by clefebvre** [comment]
I think the really valid bug here is that launching from the menu when an instance is already running should just focus it.

After that, I disagree. Most people don't trigger/launch the update manager, it starts automatically to let them know there are updates requiring their attention.
