### ISSUE TITLE
Icons are not visible anymore in LibreOffice menus. 

### ISSUE THREAD

**Issue by stephanelorrain** [linuxmint/mint20-beta#172]
Icons are not visible in Libre Office menus. Is there any option somewhere in the Mint OS to make the icons visible in the menu of Libre Office ? Icons where visible in previous Mint versions. 
The following screenshot is what we "should" see. 
![image](https://user-images.githubusercontent.com/9101553/85249358-8c5c4880-b421-11ea-8c55-20805feaafed.png)

**Comment by xenopeek** [comment]
Cinnamon, MATE or Xfce?

**Comment by clefebvre** [comment]
All afaik.

This is a design choice made upstream from us. I can't say for sure whether that's coming from LO or GTK, I'd guess GTK... if you want icons in your GTK.Menus these days, you REALLY need to want them. They're going away if you don't force the issue.

In GTK4 they'll be gone for good afaik. GNOME doesn't want icons in menus, so they're slowly but surely disappearing.

**Comment by clefebvre** [comment]
More info at https://ask.libreoffice.org/en/question/234567/cannot-enable-menu-icons-in-lo-642/

**Comment by Acheron17** [comment]
Yes, you can only get the menu icons in KDE now natively without having to make adjustments to your system.
