### ISSUE TITLE
Cinnamon: Panel icon scaling issue?

### ISSUE THREAD

**Issue by outhud** [linuxmint/mint20-beta#176]
In the LM 20 Beta with Cinnamon 4.6.3 using Mint-Y theme (also confirmed this issue on other themes), if I right click the panel, go Panel Settings and set something like Panel Height 24px and Symbolic Icon size 22px, I get a squashed LM icon as shown: https://i.imgur.com/pYx9f7n.png

Can anyone reproduce? Sometimes it only happens after I restart Cinnamon after making the change.

**Comment by xenopeek** [comment]
Duplicate of #39
