### ISSUE TITLE
ZFS is not supported during the install

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/mint20-beta#179]
It seems Linux Mint installer is not supporting ZFS installs (system disk as ZFS). That would be nice to have support in Linux Mint version 20 too.

https://ubuntu.com/blog/zfs-focus-on-ubuntu-20-04-lts-whats-new

**Comment by clefebvre** [comment]
This wasn't planned for this release.

**Comment by kkittykait** [comment]
and ZFS on LUKS?
