### ISSUE TITLE
Please explain how current release code name was chosen?

### ISSUE THREAD

**Issue by s3rj1k** [linuxmint/mint20-beta#18]
Does this is a kind of hidden reference to actual living person?

**Comment by saraaba** [comment]
Your mom

**Comment by s3rj1k** [comment]
Very mature, LOL

**Comment by saraaba** [comment]
You started it

**Comment by s3rj1k** [comment]
Perfectly legit question

**Comment by saraaba** [comment]
Perfectly legit answer

**Comment by s3rj1k** [comment]
@xenopeek Is [this](https://github.com/linuxmint/mint20-beta/issues/18#issuecomment-643808956) is an official Linux Mint position that I can reference?

**Comment by xenopeek** [comment]
@s3rj1k issue was closed as this isn't a beta bug, which is what this project is solely for. Please let the developers here focus on bugs in the beta and post other questions to the blog or forums.
