### ISSUE TITLE
Workspace Switcher Applet - Show specific icon

### ISSUE THREAD

**Issue by brianmckillop** [linuxmint/mint20-beta#181]
Cinnamon does not show the specific icon on any open app on any workspace, instead it shows a grey rectangle? This is available on LM MATE environment.

**Comment by xenopeek** [comment]
Cinnamon and MATE's workspace switchers (also Xfce's) show a visual representation of the windows open on a workspace (the rectangle you mention; for a maximized window or window fully occluding all other windows that would be all that is shown). MATE (also Xfce) adds a miniaturized icon in the rectangle representing a window iff the window is large enough. Cinnamon indeed doesn't try to fit miniaturized icons. We're in beta bug rush, there's no room now to implement new features. You can report it on Cinnamon as a feature request.
