### ISSUE TITLE
Full disk encryption not working without Internet connection

### ISSUE THREAD

**Issue by mnnguyen** [linuxmint/mint20-beta#186]
It seems an Internet connection is required to download and install cryptsetup-initramfs package  if you planned to install linuxmint 20 with full disk encryption with LUKS (see /lib/partman/finish.d/70crypto_aptinstall, line 13) This package was not required in linuxmint 19.3.  Without the cryptsetup-initramfs,  the dialog box to enter the passphrase is missing and fallback to initramfs shell.  On Ubuntu 20.04,  the cryptsetup-initramfs package is installed on the liveCD.   Maybe a warning in the release notes  should be suffice.

**Comment by kkittykait** [comment]
We need an internet connection to install Mint? That would be bad

**Comment by clefebvre** [comment]
Ah, it was removed because of https://bugs.launchpad.net/ubuntu/+source/cryptsetup/+bug/1802617. We disabled swap encryption in home dir scenarii so we might be able to put it back. I'll test to make sure.

**Comment by kkittykait** [comment]
Can we have a custom LVM partition setup within LUKS encrypted? (including swap)

This would be a deal breaker for me if I could not

**Comment by genbushi** [comment]
verified, this resolves [#19](https://github.com/linuxmint/mint20-beta/issues/19). @mnnguyen wins the internet on this day, thank you. This no doubt also saved a lot of post-release issues too.

**Comment by kkittykait** [comment]
I don't like the idea of having to have an internet connection to install an OS (and one that has yet to be locked down and secured and configured at that, that comes post install)

**Comment by clefebvre** [comment]
OK, the first battery of tests came back successful.

LVM + encryption now works after an offline installation
ecryptfs installation also still works successfully

It looks good. This is likely to be fixed in the stable ISO.

**Comment by clefebvre** [comment]
We might bump into https://bugs.launchpad.net/ubuntu/+source/cryptsetup/+bug/1802617 when we work on the upgrade path though, but we can look into that later.
