### ISSUE TITLE
 Mint 20 LMDE4  Nvidia no Hardware acceleration

### ISSUE THREAD

**Issue by matthackel** [linuxmint/mint20-beta#189]
There is no Hardware acceleration on brandnew Mint 20 LMDE4 .
No options are given to choose a driver. 
The button to refresh the Nvidia Drivers is available but not working! not at all.
is there any help for this outthere???

**Comment by xenopeek** [comment]
If you have the same issue on LMDE 4 this doesn't look to be an issue specific to the Linux Mint 20 beta, what this project is for. Suggest to ask in relevant section on the [support forum](https://forums.linuxmint.com/) for help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) this issue.
