### ISSUE TITLE
LM20 MATE - Panel system icons don't change

### ISSUE THREAD

**Issue by GilbertDube** [linuxmint/mint20-beta#191]
Hi
When I Select any icons set (Mate, Gnome, any) from Apparence - Customize...
the Update and Sound icons on the panel does not change (see picture)
All update as of today have been applied.

I tried 'Reset Panel' no change.
Did not have that problem with LM19 on same hardware.

Control: Mint-Y-Darker-Grey (same problem with any)
Border: DustBlue  (same problem with any)
Icons: MATE  (same problem with any)
Pointer: DMZ (White)

![Screenshot at 2020-06-24 13-47-23](https://user-images.githubusercontent.com/19807875/85607606-cc9b1100-b643-11ea-9fc2-c6cc9a2ab733.png)

**Comment by GilbertDube** [comment]
Hi
Just tested in Ubuntu 20.04 MATE in a VM
No problem there, all icons on the panel change.

**Comment by xenopeek** [comment]
The Update and Sound icons are symbolic icons. It's by design that these have a consistent look. See the Tray section in [New features in Linux Mint 20 MATE](https://www.linuxmint.com/rel_ulyana_mate_whatsnew.php).
