### ISSUE TITLE
Cannot boot Cinnamon on Dell XPS 13 9380 with 4k screen.

### ISSUE THREAD

**Issue by ppapachiou** [linuxmint/mint20-beta#2]
It makes no difference if compatibility mode is selected.
Ubuntu 20.04 runs fine on the same hardware.

**Comment by NikoKrause** [comment]
Do you have Secure Boot enabled?

**Comment by ppapachiou** [comment]
> Do you have Secure Boot enabled?

No.

**Comment by ppapachiou** [comment]
> > Do you have Secure Boot enabled?
> 
> No.

I tried also with Secure Boot enabled.  Same behavior.  It never reaches the desktop.  It shows only a blank screen.

**Comment by pasch256** [comment]
can you check the kernel??... open a terminal and type  uname -a and post the output. beacause maybe the problem is you using a old kernel, the lasted is 5.4.0-37.

**Comment by ppapachiou** [comment]
> can you check the kernel??... open a terminal and type uname -a and post the output. beacause maybe the problem is you using a old kernel, the lasted is 5.4.0-37.

It is the kernel that is shipping with the beta ISO.  I am trying to boot from USB stick in order to test and install on the XPS.  The USB stick works fine on another Dell laptop (Inspiron 11 3162)  and also has been used to successfully install the beta on my desktop PC.

**Comment by pasch256** [comment]
the kernel of the iso, as far i know is 5.4.0-26, unless you upgraded when you install, you still have that kernel and not the latested... the Inspiron 11 3162 have othe graphics and cpu, so is not the same of you xps, beacause have a more advance graphics and screen, so the kernel in that laptop, maybe need a more fixed kernel (the lasted).

**Comment by ppapachiou** [comment]
I can boot just fine with Ubuntu 20.04 on USB stick that uses the 5.4.0-26 kernel but not with Cinnamon and the same kernel.

**Comment by pasch256** [comment]
ok, that kill the kernel upgrade theory.

**Comment by D0ntPanic** [comment]
I have this same issue on my XPS 13. It appears to be a grub configuration issue, because I was able to get it booting perfectly by manually patching the `/boot/grub/grub.cfg` on the live image.

I commented out these lines:
```
if loadfont /boot/grub/font.pf2 ; then
 set gfxmode=auto
 insmod efi_gop
 insmod efi_uga
 insmod gfxterm
 terminal_output gfxterm#    set theme=/boot/grub/themes/linuxmint/theme.txt
fi
```

After installing it did not boot successfully. I had to edit `etc/default/grub` and set `GRUB_GFXMODE` to `1280x1024`. After that it ran perfectly.

GRUB seems to be not compatible with this system when running at the auto-selected 4k resolution. It seems to be running at 4k when you don't let it select so the issue is a bit strange.

On my other machine (an AMD desktop with a GTX 2080 Ti), Mint 20 Beta does run in compatibility mode without modification (the open source video drivers prevent it from working in non-compat mode, but that is documented). However, GRUB on the 2560x1440 display I have is almost unusuably slow on it. Entering the GRUB console, it takes multiple seconds to type a single character. There seems to be some kind of issue with modesetting in GRUB.

**Comment by DarkOwl2** [comment]
I think I'm having the same problem: GT710 graphics card driving a UHD monitor (3840x2160) via HDMI.  I can boot the LM20beta Cinnamon iso from DVD in compatibility mode (1024x768), but without selecting compatibility mode there is no output on HDMI.

The system works fine on LM18.2 Cinnamon.  I have now tried LM19.3 Cinnamon and it shows the same problem.

**Comment by clefebvre** [comment]
So hold on, let's summarize...

- You're booting 20 BETA ISO in EFI mode...
- You can see the grub menu
- When you boot, you see what?
- Do you see plymouth?
- Do you see the boot sequence if you press the left/right arrows?
- Do you get to tty with ctrl+alt+f2/f3/f4?
- Is it Xorg that's failing to start altogether? or you can't even get it to boot the OS at all? or is Xorg running but you just can't see it? (check the process list from console).

**Comment by clefebvre** [comment]
Dell XPS 13 9350 (UHD 620 Graphics) boots fine.

**Comment by clefebvre** [comment]
@D0ntPanic you had to respin a new ISO to change the grub.cfg used in live mode right?

**Comment by ppapachiou** [comment]
*   screen resolution is 4k on intel i7 with  620 graphics
  *   ubuntu 20.04 boots fine
  *   booting  20 beta ISO in EFI mode
  *   I can see the grub menu.
  *   Selecting the default or compatibility mode I get a blank screen
  *   if by plymouth you mean the logo, no
  *   left/right arrows or ctrl+alt+f2/f3/f4 does not bring up anything
  *   I don't know how to get to console.


On Thu, 2020-06-18 at 06:57 -0700, Clement Lefebvre wrote:

So hold on, let's summarize...

  *   You're booting 20 BETA ISO in EFI mode...
  *   You can see the grub menu
  *   When you boot, you see what?
  *   Do you see plymouth?
  *   Do you see the boot sequence if you press the left/right arrows?
  *   Do you get to tty with ctrl+alt+f2/f3/f4?
  *   Is it Xorg that's failing to start altogether? or you can't even get it to boot the OS at all? or is Xorg running but you just can't see it? (check the process list from console).

**Comment by DarkOwl2** [comment]
I will check the checklist and report back later.

**Comment by clefebvre** [comment]
In the grub command line (I believe you press C to get there), can you type `videoinfo` and see what it says?

**Comment by ppapachiou** [comment]
> In the grub command line (I believe you press C to get there), can you type `videoinfo` and see what it says?


![IMG_20200618_173558](https://user-images.githubusercontent.com/64209258/85034377-b516e080-b18a-11ea-8cad-5f8f6becd807.jpg)

**Comment by clefebvre** [comment]
OK, the only difference I can see between Ubuntu 20.04 and Mint 20 is the fact that we set a theme. I'll make a new ISO without the theme and give you a link.

**Comment by clefebvre** [comment]
You can get an ISO with no theme with the following command:

`wget -c build.linuxmint.com/linuxmint-20-Cinnamon-amd64-202006181132.iso`

the sha256sum for this ISO is:

`eeae61ef908a83a47206eac5ff2cb3f06b88fd92122d4e87696749c5b8b7c552`

Let me know if you can boot this one.

**Comment by ppapachiou** [comment]
this one worked.  I am writing this from the live session.

**Comment by clefebvre** [comment]
@ppapachiou excellent, can you continue testing and install it?

I'm curious to see if it works post-install, or if you need to remove `grub2-theme-mint`.

**Comment by ppapachiou** [comment]
![Screenshot from 2020-06-18 23-55-54](https://user-images.githubusercontent.com/64209258/85055550-412a0780-b18d-11ea-8c1f-d1bea4d7c29c.png)
I get IO errors while inputing user name.

**Comment by clefebvre** [comment]
Check the sha256sum and write the stick again.

**Comment by clefebvre** [comment]
I confirmed the original ISO was good here anyway, I can install it fully.

**Comment by D0ntPanic** [comment]
@clefebvre I did not spin a new ISO in my successful install. I used a hex editor to comment out the lines in the original beta ISO.

**Comment by DarkOwl2** [comment]
Just to keep everyone informed: having just arrived home I have started the download - which will take 90 minutes on my line!  I will test it on my rig as soon as I can and report back.

**Comment by DarkOwl2** [comment]
No joy, very similar results.  This is a Ryzen5 with GeForce GT 710 graphics via HDMI to a 3840x2160 screen.

>> You're booting 20 BETA ISO in EFI mode...

In MBR boot I get a graphical grub menu, and EFI it's just text.  For what follows this is from the EFI version.

 >>  *   You can see the grub menu

Yes

>>  *   When you boot, you see what?

A small circular LM logo in the centre of the screen (bearing in mind this is a hi-res screen), followed by a few lines of text, and then no output.

>>  *   Do you see plymouth?

Plymouth is what - a desktop theme?  Not before, and not now.  The screen doesn't just go black, the video card actually stops outputting anything on HDMI at all and the monitor shuts down.

>>  *   Do you see the boot sequence if you press the left/right arrows?

Yes

>>  *   Do you get to tty with ctrl+alt+f2/f3/f4?

Yes.  Ctrl-Alt-F4 got me a text login prompt, video output started up.

>>  *   Is it Xorg that's failing to start altogether? or you can't even get it to boot the OS at all? or is Xorg running but you just can't see it? (check the process list from console).

Help needed.

Note this sequence looks (to me) the same as when I try to boot 19.3 or the original 20 beta from the iso.  Should I be installing from the grub menu?  My working 18.2 was from a bootable magazine cover disk.  I confirmed the hash of the new beta download, and the DVD burner was set to verify.

![482BA6A1-0332-4620-BF87-3ED02C17D8F8](https://user-images.githubusercontent.com/67048140/85081901-4440ea00-b1c5-11ea-9f88-54e7e0ca4e27.jpeg)

(subsequent images of boot process deleted - see dmesg dump in [later post](https://github.com/linuxmint/mint20-beta/issues/2#issuecomment-646518069))

**Comment by ppapachiou** [comment]
> 
> 
> I confirmed the original ISO was good here anyway, I can install it fully.

I checked the checksum and it was correct.  I switched from a usb-c to usb-a cable (that came with the laptop) to a Dell usb-c mini dock and the installation finished sucessfully.
However upon reboot I get the grub menu and then when I boot, the blank screen again.
Arrow keys don't work and no tty with ctrl+alt+f2/f3/f4.
nomodeset, nouveau.noaccel=1, and noapic noacpi nosplash irqpoll did not help either.

I then used the live-usb stick to edit grub.cfg and comment out the lines setting the linuxmint theme and was able to boot.  I installed all the updates and now the laptop boots with the linuxmint theme selected.

**Comment by DarkOwl2** [comment]
More info (Ryzen5/GT710/3840x2160):

Left/right keys don't work in MBR-mode boot; no access to console login via Ctrl-Alt-F2/F3/F4.  These do work if I boot the DVD in EFI mode.

Grub videoinfo command:

![F85409F4-9F53-42D1-9D0A-5EAB2D0E6CBC](https://user-images.githubusercontent.com/67048140/85110728-3d3cca80-b20b-11ea-8d65-262bab50cfb4.jpeg)

dmesg output:

[dmesg.txt](https://github.com/linuxmint/mint20-beta/files/4803463/dmesg.txt)

/dev/sdg1 is a USB stick I plugged in to export the dmesg output.

inxi -Fxxxrz output:

[inxi.txt](https://github.com/linuxmint/mint20-beta/files/4803547/inxi.txt)

Any other info you want, just let me know (including instructions for getting it).

Is this relevant?:

```
[    0.214592] Trying to unpack rootfs image as initramfs...
[    0.377394] Initramfs unpacking failed: Decoding failed
```

**Comment by DarkOwl2** [comment]
As I am using different hardware from the original post, and my observations are divergent, do you want me to open a new issue and transfer my posts there?

**Comment by clefebvre** [comment]
@DarkOwl2 no, you're using an NVIDIA card which Nouveau (the open-source drivers) fail to handle. You just need to use compatibility mode to boot in live mode to work around this, and then post-install you need to use `nomodeset` and install the NVIDIA drivers as described in the release notes.

**Comment by clefebvre** [comment]
@ppapachiou thanks.

So what we'll do for sure is remove the theme from the live grub menu. And then either we'll ship without grub2-theme-mint or we'll add instructions in the release notes.

**Comment by DarkOwl2** [comment]
> @DarkOwl2 no, you're using an NVIDIA card which Nouveau (the open-source drivers) fail to handle. You just need to use compatibility mode to boot in live mode to work around this, and then post-install you need to use `nomodeset` and install the NVIDIA drivers as described in the release notes.

Sorry to be dim but could you point me at the relevant information / resource?  (OK - I think I've found it, but the video doesn't play on my iPad: [https://www.linuxmint.com/rel_ulyana_cinnamon.php](url), "Solving freezes during the boot sequence")

May I also comment that there is an audience out there who might try live-booting Mint because it's high on the list of recommended Windows replacements, find it doesn't work on their hardware and give up (probably because they don't have the knowledge and/or technical ability to investigate and do anything about it, even with instructions).

18.2 boots and runs fine on my hardware without any fiddling.  Based on just one test, 19.3 doesn't.  I strongly recommend the release version of LM20 should too, and I am willing to help achieve that.  Overall it will be much more welcoming to the proportion of potential users with Nvidia hardware.

Also, I would very much like a rescue disc that boots without installation!

**Comment by DarkOwl2** [comment]
I have installed from compatibility mode, changed the grub config as described in the release notes (a few more words of explanation would have been helpful, such as "press e to edit the configuration"), booted to desktop, installed NVidia drivers, rebooted.  I now have a graphical login screen in 4K.

What I can't do is login except with the on-screen keyboard: the gui responds to mouse but not keyboard.
