### ISSUE TITLE
Python Not Set

### ISSUE THREAD

**Issue by charles-vomacka** [linuxmint/mint20-beta#21]
Entering python at the command prompt results in - python: command not found. Specifying the version of python works, e.g. python2 or python3. I do not know if this is intentional, but is different behavior than in previous versions of Mint.

**Comment by NikoKrause** [comment]
You can install the `python-is-python2` or `python-is-python3` package, depending on your preferences.

**Comment by charles-vomacka** [comment]
Thank you for the quick reply. Did I miss this in the Release Notes?

**Comment by xenopeek** [comment]
> Did I miss this in the Release Notes?

Under Other issues in the Linux Mint 20 release notes it says: "Linux Mint 20 is based on Ubuntu 20.04. Make sure to read the Ubuntu release notes."

There you can find this information about `python` not being set by default: https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default
