### ISSUE TITLE
Mate Menu - can't reorganize favorites

### ISSUE THREAD

**Issue by mirostauder** [linuxmint/mint20-beta#22]
When customizing Favorites in the menu, moving the items to a different position doesn't work.
Dragging a favorites icon to a desired position, after release it just jumps back.

**Comment by arsivci** [comment]
Affects me, too.

**Comment by Ruessel** [comment]
Me too.

**Comment by mtwebster** [comment]
Did this work in the previous version?

**Comment by xenopeek** [comment]
It did. I tested on Linux Mint 19.3 MATE and you can drag one icon in favorites on top of another to reorganize them (the dragged icon is put before or after the target icon).
