### ISSUE TITLE
XFCE: Suspend issues with laptop lid

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20-beta#23]
I have a Dell XPS 9570 running Manjaro that I sometimes test other distros on. Yesterday, when I tried the Mint Beta, I found that, while suspend works normally with the power button and such after adding `mem_sleep_default=deep` to the kernel parameters, using the laptop lid to suspend the machine was inconsistent. The problem seems to be related to `light-locker` for XFCE, however I do not have these issues on Manjaro. Also, I should mention that switching to `xfce4-screensaver` for locking the screen instead did not fix the issue either. I've had problems with this in the past on upstream Ubuntu but I couldn't get any attention to the issue.

**Comment by pcspecialist** [comment]
This has been an issue that has plagued Ubuntu-based XFCE installations for a long time on every laptop I've tried it on.

**Comment by ghost** [comment]
> This has been an issue that has plagued Ubuntu-based XFCE installations for a long time on every laptop I've tried it on.

I'd reported it several times on Launchpad and the Ubuntu forums before I hated `snapd` but nobody ever listened. I didn't mention this because it wasn't important. Will there ever be anything done about this or is this just sort of a middle finger to the user? Mint still has several options:
* Create a patched package for `light-locker`, `xfce4-power-manager`, `xfce4-screensaver`, or whatever is causing this.
* Use the distro's influence to talk to the Ubuntu guys

However, both of these options are extremely unlikely as this bug has been shafted. So I guess Mint won't end up being very user friendly after all.

**Comment by pcspecialist** [comment]
I too reported it but it seems there is no interest in fixing it.  That said, Mint Xfce is still my favorite distro.

**Comment by clefebvre** [comment]
> I hated
> nobody ever listened
> a middle finger to the user
> I guess Mint won't end up being very user friendly after all

Can we turn down the drama a notch here?

When you refer to an existing bug which was already reported, you need to link to it.

Here I'll save you the trouble. You're at the observation phase. **Your** work is not done. I can run the Xfce edition on a laptop here and test lid sleep (we do that for all QA phase by the way, it's one of the tests), and come back to you and give you the exact opposite observation: It works.

You've a few things to find out before making a bug report. You need to know what triggers the issue, in what conditions, and what component is responsible for it.

Obviously if it happens in Ubuntu as well, then it's upstream from us, but even if we go and talk to the Ubuntu devs, if we don't know what we're talking about, they're not going to do anything about it.

Right now we've got... lid sleep "sometimes" doesn't work on "some hardware", we reported it against "xfce4-power-manager" but we're not really sure it's related to it.

https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/

The first thing I'd do if I were you is test another edition with the same kernel, Mint 20 BETA MATE for instance. That will allow you to focus more on the source, whether that's kernel/systemd/lid-events on the lower level or the Xfce DE itself.

**Comment by clefebvre** [comment]
systemd logs and power-manager logs might be useful too. I forgot to mention these. You should be able to make sure systemd handles the lid event, and that power-manager is reacting to it.
