### ISSUE TITLE
Double interface scaling not working.

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/mint20-beta#27]
Original issue posted here: https://github.com/linuxmint/cinnamon/issues/9366

---

```
 * Cinnamon version 4.6.3
 * Distribution - Mint 20 Beta
 * Intel no drivers
 * 64 bit
 ```

**Issue**

Double interface scale not working

**Steps to reproduce**

Go to settings -> display -> base interface scale
Choose Double from the dropdown

The screen will resize to a quarter and switch back. The "Do you want to keep these settings" dialog pops up, but nothing was changed and interface scale is back to "normal".

Except now, the "double" option is gone from the interface scale dropdown.

**Expected behaviour**

Interface gets bigger in size like on Mint 19

**Other information**

Thinkpad Yoga X1

**Comment by dahunt** [comment]
I also see this issue on dual 4k monitors.....

**Comment by mtwebster** [comment]
Hi can you check out this comment:
https://github.com/linuxmint/cinnamon-control-center/pull/238#issuecomment-646734935

I've uploaded some test packages that hopefully help resolve some of the issues people are having with display configuration.

Thanks

**Comment by clefebvre** [comment]
Hi,

This is upstream from us unfortunately and a limitation between xrandr and the GPU driver. What we'll do is make it clearer fractional scaling is ON and advertise it as an experimental feature with limitations.
