### ISSUE TITLE
Software Manager doesn't install Chromium

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20-beta#30]
Linux Mint's Chromium package (in the Software Manager, not through the command line, where it is obvious the reason why chromium doesn't work) only installs a dummy package. The software manager should install Chromium from the official location or through snap instead of doing nothing and directing the user to download it through the website manually through the description.

**Comment by xenopeek** [comment]
Just making a note for anybody that wants to install Chromium now, there's a tutorial over on the forums covering various ways to install Chromium: https://forums.linuxmint.com/viewtopic.php?f=42&t=321953

**Comment by clefebvre** [comment]
We're not going to do with Flatpak, what Ubuntu did with Snap. MintInstall does show the same package description as APT.
