### ISSUE TITLE
Linux Mint 20: apt is not working with * symbol

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mint20-beta#34]
Hi, you can look this issue. https://github.com/linuxmint/mintsystem/issues/114

**Comment by xenopeek** [comment]
Linux Mint's apt uses /usr/bin/apt for package installs and removals. From /usr/bin/apt version 2.0, which is used on Linux Mint 20/Ubuntu 20.04 LTS, wildcards like `nvidia-prime*` are not supported and instead it uses aptitude style [patterns](https://manpages.ubuntu.com/manpages/focal/man7/apt-patterns.7.html) like `~n^nividia-prime` for the same. This is a contentious change and upstream is reverting the removal of wildcards: https://lists.debian.org/deity/2020/03/msg00055.html

For your example the syntax would be: `apt purge ~n^nividia-prime`. Meaning, purge all packages with name (~n) starting (^) with nvidia-prime. BTW you don't need to use `sudo` with `apt`.
