### ISSUE TITLE
Driver manager broken

### ISSUE THREAD

**Issue by frozenMustelid** [linuxmint/mint20-beta#36]
Tested LM 20 Beta on a live DVD a few days before it was officially announced. The Driver Manager wouldn't load, though I suspect this might be an issue exclusive to the live environment. A screenshot is available on the forum post:

https://forums.linuxmint.com/viewtopic.php?f=60&t=321932&p=1828974#p1828974[](https://forums.linuxmint.com/viewtopic.php?f=60&t=321932&p=1828974#p1828974)

**Comment by kelebek333** [comment]
Disable CD-ROM repository from Mintsources and try again.

![mintsources-cdrom](https://user-images.githubusercontent.com/1300133/84607236-d179fb00-aeb4-11ea-8274-3b6b1a180dc5.png)

**Comment by frozenMustelid** [comment]
Disabling the CD-ROM repo lets the driver manager load. Thanks!

**Comment by LinuxOnTheDesktop** [comment]
So the Driver Manager will not load when using the live version of Mint? OK, but the 'failed to download . . check your Internet connection' message is not helpful. Indeed it misleads!
