### ISSUE TITLE
Add traditional layout option back to mintwelcome

### ISSUE THREAD

**Issue by Lurux** [linuxmint/mint20-beta#38]
I dunno if this is the right place for this but hey ! I'm desperate enough to come here and beg you to keep this option available. I and many other users find the "launchers + full window list" combo way more practical than the default "grouped windows with pinned apps".

**Comment by netjerykhet** [comment]
I agree. This seems a rather arbitrary decision, and making it more difficult for users to change the window list only has the effect of making it more difficult. This option, I think, should be retained.

**Comment by smurphos** [comment]
I personally prefer this idea - https://github.com/linuxmint/cinnamon/issues/9226

**Comment by xenopeek** [comment]
smurphos has a tutorial over on the forums if you want to set traditional layout right now: https://forums.linuxmint.com/viewtopic.php?f=42&t=321872

**Comment by frozenMustelid** [comment]
You can kind of fix this yourself, but it's unintuitive. You have to right click on the bar and go into Panel Edit mode. Remove the Grouped Window List applet from the panel and replace it with the Window List applet.

**Comment by Lurux** [comment]
> I personally prefer this idea - [linuxmint/cinnamon#9226](https://github.com/linuxmint/cinnamon/issues/9226)

That sounds great but at least keep the welcome screen toggle until we get this.

@xenopeek @frozenMustelid of course I know how to do that, but a new user won't. This is a really dumb way of putting things.

**Comment by xenopeek** [comment]
I just added the comment for others finding the same.

**Comment by Nebelkind** [comment]
May one suggest, that a toggle switch should  also save the current configuration, so you can switch between the two layouts without losing user customisations done to any of the involved applets by switching? A permanently avalaible switch would be appreciated either way.

**Comment by NikoKrause** [comment]
Fixed https://github.com/linuxmint/mintwelcome/commit/d7f305d409bab0358cd8a5a34576a4ac44f08169
