### ISSUE TITLE
Bugged width of Mint menu icon after reducing panel height

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/mint20-beta#39]
The width of Mint menu (applet) icon is bugged after reducing the panel height. 
Changing the icon size on the menu configuration panel to match panel's configurations solves the problem. For instance, setting the height to 20px, mint menu icon size to 18px and simbolic icon size (in panel options) to 18px.
However, I use the same configurations on Mint 19 and this fix is not needed. 

Bugged:
![Captura de tela de 2020-06-14 21-49-23_compressed](https://user-images.githubusercontent.com/1660320/84608721-1d637a80-ae8a-11ea-8ebc-b5b95ab59026.png)

Fixed:
![Captura de tela de 2020-06-14 21-58-34_compressed](https://user-images.githubusercontent.com/1660320/84608760-4a179200-ae8a-11ea-916b-caa166d3d72f.png)

**Comment by mtwebster** [comment]
Is this cinnamon?

**Comment by BrunoNZ** [comment]
Yes. Sorry for not adding this info.

**Comment by BrunoNZ** [comment]
Nice! Thanks!

**Comment by outhud** [comment]
I still see this issue on Cinnamon 4.6.6.

**Comment by xenopeek** [comment]
It's fixed for final release. Here is it with panel height 20px, menu icon height 18px and symbolic icon height 18px as per original issue:

![image](https://user-images.githubusercontent.com/21159972/85607934-df6a1180-b654-11ea-813f-4a2fa87166ac.png)
