### ISSUE TITLE
Missing PT-Br translations

### ISSUE THREAD

**Issue by BrunoNZ** [linuxmint/mint20-beta#40]
There some missing PT-Br translations.

* Terminal -> Profile -> Colors (It's translated in Mint 19):
![Captura de tela de 2020-06-14 22-04-55_compressed](https://user-images.githubusercontent.com/1660320/84609026-80a1dc80-ae8b-11ea-9695-9e77de003d9c.png)

* Monitors configuration panel:
![Captura de tela de 2020-06-14 22-05-49_compressed](https://user-images.githubusercontent.com/1660320/84609054-a8914000-ae8b-11ea-92f1-607bd7f27f42.png)

**Comment by xenopeek** [comment]
Related to #25 where several other translation issues for PT-Br are mentioned. There is a [Linux Mint Translation Guide](https://linuxmint-translation-guide.readthedocs.io/en/latest/) if you would help improve translations.

**Comment by NikoKrause** [comment]
The second picture is fixed. 
I can reproduce the issue in the first picture with German l10n.
I can't find the string in the gnome-terminal code though :(

**Comment by clefebvre** [comment]
The transparency settings were removed by GNOME in gnome-terminal. Ubuntu re-adds them via a patch, but they rely on msgids which no longer exist in gnome-terminal, so this can't be translated.
