### ISSUE TITLE
APT: could not configure libc6:i386 when installing WINE

### ISSUE THREAD

**Issue by frozenMustelid** [linuxmint/mint20-beta#43]
I got two error messages from apt when I installed WINE and PlayOnLinux. The first says "E: Could not configure libc6:i386" and the second says "Could not perform immediate configuration on libgcc-s1:i386. Please see man 5 apt.conf under APT::Immediate-Configure for details. (2)"

I don't know what this means but WINE seemed to run fine anyways. I tried the GOG version of Hitman - Codename 47 (file informed me that it was a 32-bit Windows executable) and it ran about like I expected, though I will admit that I have never played this game before. It was installed through the POL script for this game, which includes downloading Wine 3.0.3.

The only problem I noticed was that Mint really hates the resolution of this game, but 4:3 fullscreen WINE programs being run on a 16:9 monitor has caused problems for Mint ever since Mint 18. It ran fine when I told WINE to emulate a virtual desktop.

**Comment by clefebvre** [comment]
This worked just before QA. It looks like some packages are now missing in the Ubuntu 20.04 repositories.

Similar:

https://github.com/Winetricks/winetricks/issues/1525
https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1871268
https://askubuntu.com/questions/1245173/problem-installing-wine-in-ubuntu-studio-20-04

**Comment by clefebvre** [comment]
Still happening. It doesn't really seem to affect anything though. I'll close since it's upstream.
