### ISSUE TITLE
Transparent terminals act strangely when button set is Mint-X

### ISSUE THREAD

**Issue by frozenMustelid** [linuxmint/mint20-beta#44]
Translucent terminal windows act very strangely when you use the Mint-X button set (radio button, checkbox). The most obvious glitch is that they usually, but not always, show the desktop background instead of the window behind them, but WOULD show the shadow borders of other windows. I'm including screenshots of some of the issues I've seen with them, but some of the glitches I saw would fix themselves when you try to screenshot it. One of these other glitches was other windows leaving trails when dragged across one of these translucent terminal windows.

I was using the Cinnamon desktop environment. My graphics card is an XFX Radeon RX 460.

![Screenshot from 2020-06-15 00-33-13](https://user-images.githubusercontent.com/31948457/84631474-70a1f100-aebb-11ea-91f8-0573458d605e.png)

![Screenshot from 2020-06-15 00-28-27](https://user-images.githubusercontent.com/31948457/84631551-93cca080-aebb-11ea-8d02-854c5426a324.png)

P.S.: This is low priority to me. I don't even use transparent terminal windows on my Mint install, this is just something I noticed in the live environment and decided to bug report anyways on behalf of people who do use them. However, I do use Mint-X.

**Comment by xenopeek** [comment]
On the linked issue is noted a workaround: in Terminal Preferences disable Use colors from system theme, disable Use transparency from system theme and enable Use transparent background and set slider to your preference.

![workaround](https://user-images.githubusercontent.com/21159972/84651634-92769480-af0a-11ea-9f16-d048323d3b1f.png)

**Comment by clefebvre** [comment]
We might remove the transparency by default. I also know quite a few people aren't completely keen on it...

**Comment by clefebvre** [comment]
Fixed in mint-themes 1.8.6.
