### ISSUE TITLE
Notification to install graphics driver each time I start the pc. 

### ISSUE THREAD

**Issue by hammadimir** [linuxmint/mint20-beta#47]
Whenever I turn on mint 20 in a virtualbox, a desktop notification appears on the desktop which tells me to install a gpu driver. Upon clicking the button to install, it goes with the driver manager. After updating the cache, the driver manager says: no third proprietary driver is in use. There isn't an option to install a driver. So I close this window. After booting again, this notification reappears. Is it really an os issue or virtualbox issue?

My laptop: HP Elitebook 840 G1 (i7 4th gen, HD graphics 4400)
Environment: Oracle virtualbox. 

I have attached some screenshots.
![IMG_20200615_123923](https://user-images.githubusercontent.com/66902991/84640199-336d4b80-af1b-11ea-984d-e690b78a9f39.jpg)
![IMG_20200615_123856](https://user-images.githubusercontent.com/66902991/84640252-3ec07700-af1b-11ea-9c0c-4e6d701aa97d.jpg)
![IMG_20200615_123828](https://user-images.githubusercontent.com/66902991/84640265-42ec9480-af1b-11ea-9e8a-efa91293859c.jpg)

**Comment by kelebek333** [comment]
Hi,

Can you post outputs of folllowing command.

`inxi -SMGxx`

**Comment by kelebek333** [comment]
Can you look that link about Virtualbox. https://www.linuxmint.com/rel_ulyana_cinnamon.php

> **Virtualbox**
> 
> **Black screen**
> 
> If the screen is black when launching Linux Mint in Virtualbox, change the VirtualBox graphics controller to "VMSVGA". Do this by opening up the settings for your VM and select Display -> Graphics Controller.
> 
> **Garbled screen**
> 
> If the screen is garbled when launching Linux Mint in Virtualbox, switch to console with HOST+F1 (e.g. the RIGHT Ctrl key, no ALT) and back to tty7 with HOST+F7.
> 
> Another workaround is to disable "nested paging" (in the System -> Acceleration settings) and to increase the video memory to 128MB (in the Display settings).
> 
> Note: This issue only affects the live session. You don't need these workarounds post-installation.
> 
> **Guest Additions**
> 
> To add support for shared folders, drag and drop, proper acceleration and display resolution in Virtualbox, click on the "Devices" menu of Virtualbox and choose "Insert Guest Additions CD Image". Choose "download" when asked and follow the instructions.
> 
> For more info, read Installing the VirtualBox Guest Additions.

**Comment by pasch256** [comment]
my workaround in virtulbox : go display and check 3D acceleration. no more driver manager.

**Comment by hammadimir** [comment]
> my workaround in virtulbox : go display and check 3D acceleration. no more driver manager.
Yeppp, it worked for me. Thank you very much :)
