### ISSUE TITLE
After install of Steam: Missing libc.so.6

### ISSUE THREAD

**Issue by kongreddgrass** [linuxmint/mint20-beta#48]
If i install Steam and start it, the error occured:

> Error: You are missing the following 32-bit libraries, and Steam may not run:
> libc.so.6
> Error:
> You are missing the following 32-bit libraries, and Steam may not run:
> libc.so.6

It's running fine with a install of libc6:i386. I think, it's better to implement it in LM20. 
A Windows newcomer wouldn't know what to do at this point and immediately installs Windows again. We should make it a little easier for the user...

**Comment by xenopeek** [comment]
Curious that the source package doesn't depend on libc6:i386 if that is what is needed: https://packages.ubuntu.com/focal/steam

**Comment by kongreddgrass** [comment]
Steam needed this packages: libgl1-mesa-dri:i386, libgl1:i386, libc6:i386.
After I reinstalled Steam with all the reinstalled dependencies, I was asked (which didn't come before) to install the dependencies. These could be pre-installed in this case as well.

**Comment by xenopeek** [comment]
My bad, package `steam` is virtual and actually installs `steam:i386` which thus depends on `libc6:i386`.

Can you clarify how you installed steam and whether this is on the LM20 beta LiveISO, from a LM20 beta install or perhaps you upgraded in place from LM19.x?

**Comment by BrunoNZ** [comment]
I believe the problem lies on the fact that there are two ways to install steam:
* steam-installer - Installer for Valve's Steam digital software delivery system
* steam - Valve's Steam digital software delivery system

I used "steam-installer" package, and everything is perfect. 

Wine has the same problem. It's really confusing to know which one is the right one.

**Comment by frozenMustelid** [comment]
I installed the package "steam" and didn't have a problem. Does it only happen when you log in or try to start a game? Steam always wants to email me when I log in from a new PC, so I didn't try that. However, I was able to install Steam and start it from both the GUI and terminal, neither of which gave me errors.

**Comment by gergo424** [comment]
I reproduced the problem with the installer DEB package from https://store.steampowered.com/ (i386 dependencies were not installed in this way)

I've no problems from default repo's 'steam' or 'steam-installer' so I think this isn't a Mint-related bug.

**Comment by kongreddgrass** [comment]
This was in a fresh LM20 Beta install.
Yes, i install it with the deb-package from steam-website.
I didn't know that steam-installer from the repo install the depencies.
So i think, we can close this ticket. :)
