### ISSUE TITLE
Clock applet does not show weather

### ISSUE THREAD

**Issue by pepa65** [linuxmint/mint20-beta#49]
The Clock applet, I love it, and I don't strictly require the weather (I want the map with the locations and the daylight/nighttime shading!!) but the weather here (2 different new installs) doesn't work, for the first time in many years: no icon, no temperature etc.

**Comment by xenopeek** [comment]
Applet for Cinnamon, MATE or Xfce?

There is an issue with weather information servers (servers are being migrated) that has caused intermittent outage last few weeks: https://forums.linuxmint.com/viewtopic.php?f=206&t=320757

**Comment by pepa65** [comment]
Sorry for not being clear, this is about the Mate Clock applet.

**Comment by xenopeek** [comment]
The MATE Clock applet uses the same libmateweather library as the Weather Report applet and is thus suffering from the same issue that the weather information servers used by that library have intermittent outages right now. Upstream issue: https://github.com/mate-desktop/libmateweather/issues/80

**Comment by pepa65** [comment]
The one on Ubuntu MATE 18.04 is still working though, maybe switch providers??
