### ISSUE TITLE
Installer creates and uses empty efi-partition with bios-setup

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/mint20-beta#5]
mint-20-cinnamon (64bit)
The Installer creates an empty 512MB volume which is mounted at /boot/efi at the installed OS.

Using qemu/kvm with an empty/new virtual disk:

Perform installation with an bios (non-efi) setup:
Default installation: use entire disk, default ext4 fs, no lvm, no luks, no ecryptfs
no drivers installed
german keyboard setup - english locales - german/berlin tz

Result after boot:

lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0     11:0    1 1024M  0 rom  
vda    252:0    0   15G  0 disk 
**├─vda1 252:1    0  512M  0 part /boot/efi**
├─vda2 252:2    0    1K  0 part 
└─vda5 252:5    0 14,5G  0 part /

sudo ls -al /boot/efi/
total 8
drwx------ 2 root root 4096 Jan  1  1970 .
drwxr-xr-x 4 root root 4096 Jun 12 18:33 ..

cat_ /etc/fstab
....
**UUID=F35C-AFEC  /boot/efi       vfat    umask=0077      0       1**
...

expected result:
no efi-partition being setup with a bios-setup using mbr-style partitioning

note: 
if the installer would allow to use a gpt-style partition-table (at a later version), a bios-partition might be required - which is not the case atm

**Comment by clefebvre** [comment]
Thanks @orcus-de, it looks harmless to me. I'm not sure whether that's a change or an oversight on partman-auto or ubiquity but it looks upstream from us.

**Comment by Wilhelm79** [comment]
Hi Clem,

Can attest that's an Ubuntu upsteam bug as it appeared on the 20.04 Ubiquity installer while creating a new install (same as orcus-de : ext4, full-disk scheme, no lvm, LUKS...etc) on a legacy/BIOS system.

Cheers (and thanks for this new release !!)

**Comment by clefebvre** [comment]
Thanks @Wilhelm79

**Comment by orcus-de** [comment]
yup - agree on: it shouldn't affect anything in a negative way - it's just an empty partition being mounted - just a bit surprising.
