### ISSUE TITLE
Zoom level 125% feature makes the display blurry and causes screen tearing

### ISSUE THREAD

**Issue by gergo424** [linuxmint/mint20-beta#55]
In LM20 Cinnamon Edition Beta when I set the laptop's internal display 'Zoom level' feature to 125% with 1920x1080 original resolution the display goes blurry (more blurry than in 1366x768 resolution!) and screen tearing appears.

If I'm right, this will be the 'fractional scaling' feature what promoted in the release notes and behaving the same as in Ubuntu 20.04...makes more trouble than benefit (sadly).

The screen tearing clearly visible in this test video with 125% zoom level:
https://youtu.be/0RvIbVmCOxg

If I'm wrong and the 'Base interface scale' setting stands for fractional scaling than I've found another problem, because the only options are 'Normal' and 'Hi-DPI' for me.

Tested on: 
Dell XPS 13 9360
Intel Core i5-8250U
Mesa Intel(R) UHD Graphics 620 (KBL GT2)

**Comment by themotu** [comment]
Definitely less crisp for me also. I had tried this from older mint using cinnamon 4.6 and it seems to have looked better back then.

**Comment by dahunt** [comment]
seeing the same blurry issue here as welll. Additionally, cannot change Base interface scale to HiDPI.  It just stays in normal mode... 

Dell precision 7740 with Nvidia Quadro RTX4000 and  dual external Ultrasharp 32" 4K displays

**Comment by gergo424** [comment]
I don't know if this blogpost is relevant, but maybe useful enough about the problem:
http://octavifs.me/post/hidpi-support-on-ubuntu-19-04/

With serious vison defects of my eyes I'm waiting for years for a good solution to make objects sizes comfortable on a 13" inch screen under 1080p resolution.

For me font scaling is the only (but not the most enjoyable) workaround in the last 3+ years, but I'm still looking forward for better solutions.

**Comment by dominalien** [comment]
I'm seeing the exact same behaviour. Setting the interface scale to hi-dpi makes everything very crisp again, but performance tanks (basic stuff like moving windows around, playing videos, moving around the 3D view in Blender). I'm on Intel Core i5-7200U with HD Graphics 620.

**Comment by mtwebster** [comment]
Hi, please check out the comment here:
https://github.com/linuxmint/cinnamon-control-center/pull/238#issuecomment-646734935

As for the 125% some hardware just won't be able to handle this unfortunately - intel graphics in particular (though that's not always necessarily true).

I'd appreciate any feedback if anyone can test these.

Thanks

**Comment by dominalien** [comment]
It's exactly as before. Enabling 125% makes the screen blurry and there's tearing.

**Comment by dominalien** [comment]
One change is that before I had only 75%, 100% and 125% and now I have a lot more.

**Comment by clefebvre** [comment]
Hi,

This is upstream from us unfortunately and a limitation between xrandr and the GPU driver. What we'll do is make it clearer fractional scaling is ON and advertise it as an experimental feature with limitations.

**Comment by gergo424** [comment]
Dear @clefebvre can you point the issue(s) about the limitation please? Is this a known issue/bug somewhere?

I can't find any relevant information on the internet.
