### ISSUE TITLE
Nvidia mode doesn't scale external monitor

### ISSUE THREAD

**Issue by olegmikul** [linuxmint/mint20-beta#56]
After switching to Nvidia driver my external monitor (4k) keeps scaling ratio as 2x, even I have explicitly setup different values, e.g. 1.75. In Intel graphics mode everything is scaled as expected.

**Comment by clefebvre** [comment]
@olegmikul please provide a screenshot of your display settings.

**Comment by olegmikul** [comment]
After some updates (?) it works now fine in Nvidia mode.

**Comment by olegmikul** [comment]
Should I close an issue?

**Comment by olegmikul** [comment]
Anyway, here is a screenshot:
![Screenshot from 2020-06-17 12-50-42](https://user-images.githubusercontent.com/14209920/84943541-59b8f580-b099-11ea-8951-64dbfc580224.png)

**Comment by clefebvre** [comment]
Yes, if you can't reproduce it. Re-open a create a new one if you see it happen again or are able to trigger it.
