### ISSUE TITLE
Wired USB Mouse occasionally misbehaving  

### ISSUE THREAD

**Issue by olegmikul** [linuxmint/mint20-beta#57]
At some random point my USB wired mouse start to misbehave - mouse movement is tracking, but input (left button) is not working. Wireless USB mouse seems to be working fine. Happened with two different wired USB mouses.

**Comment by clefebvre** [comment]
I'm sorry @olegmikul, this is only an observation. It needs more troubleshooting before it can be looked at as a bug report.

For more info on troubleshooting: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/
