### ISSUE TITLE
warpinator can't see other computers, sftp and rdp can

### ISSUE THREAD

**Issue by olegmikul** [linuxmint/mint20-beta#58]
Cinnamon 20-beta.

Warpinator can't see other computers, even when I can seamlessly use sftp file transfer or remote desktop connections. Actually, I don't need warpinator, since I can handle file transfer in Krusader with enabled sftp protocol. But it seems like warpinator is the big item ticket for Mint-20, so it would be better to fix it.

**Comment by saraaba** [comment]
Warpinator uses zeroconf and zeroconf is avahi daemon
is avahi daemon running (it is by default I believe) and is listening opened on the firewall (which is disabled by default) for discovery? (it uses UDP to listen to on-link broadcasts)
I think it is port 5353 for avahi, you can see it in the UFW firewall report tab if you use that

**Comment by olegmikul** [comment]
I've tried both disabled firewall and enabled with open ports (5353 and 54629). Still no luck.

**Comment by saraaba** [comment]
Is avahi daemon running? (It should be by default I believe)

Are the same computers in the same broadcast doman (network, on-link, subnet, lan, vlan)?

You haven't named your network domain .local have you? (bad choice if you have). .local is now reserved ( https://tools.ietf.org/html/rfc6762 )

**Comment by olegmikul** [comment]
Yes, avahi-demon running on all computers. 

I am using just IP addresses, I don't have my network domain name.

**Comment by NikoKrause** [comment]
So you have to computers with Mint 20 on both. Firewall turned off on both. Warpinator running on both. And both computers are connected to the same network / wifi?

(Also default settings in warpinator? Or did you changed the settings?)

**Comment by mtwebster** [comment]
Are both computers running Mint 20?  If not, the other machine should be running at minimum version 1.0.3, or else connection will fail. (This won't be an issue moving forward, but this was an initial hiccup).

**Comment by olegmikul** [comment]
No, one computer is with Sparky Linux (latest rolling edition), another is with Mint 20. I didn't assume both should be Mint, also I didn't assume both should run warpinator. If that is the case - it is ok, assuming it is an initial hiccup. Just better definition of functionality can help. Anyway, now I understood - "it is not a bug, it is a feature"  :)

**Comment by mtwebster** [comment]
You don't need to be running mint at all, but you do need to run warpinator.
