### ISSUE TITLE
Ubiquity: incorrect min disk size

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint20-beta#59]
Step 1: boot using the beta ISO using VirtualBox.
Step 2: use that virtualised live session to try to install the beta.
Result: installation fails with this self-contradictory error message: 'You need at least 10.7GB disk space to install Linux Mint. // This computer has only 10.7 GB.'

That the cause of this problem is a dynamic disk should appear in the Mint release notes but does not (and neither could I find it in the Ubuntu release notes). The problem has been reported more than once on the Mint forum. See for instance [here](https://forums.linuxmint.com/viewtopic.php?t=281714).

Also, a self-contradictory error message is never good!

EDIT: And when I switched to a fixed-size disk, Mint's installer told me a few times that there was file mismatch - but clicking 'retry' each time allowed the installation to continue. 

Also, it is unclear what the 'skip' button does when one is installing language packs. I think it will skip installing the language pack - but the button is rather close to the slide-show, so one can think that _the slide-show_ will get skipped. I submit that this needs changing.

**Comment by acotty** [comment]
I was able to install LM20 beta on VirtualBox 6.1.10 using a dynamic disk that I configured to be a max of  100GB and it installed manually without a problem.

I am using Windows 10 version 2004. 

What was the max size of the dynamic disk did you specify? I hope it was at least 20GB, but preferably more as it will grow until you zero the sectors and then compress the VDI to get the zero sectors back.

**Comment by LinuxOnTheDesktop** [comment]
I am not sure what maximum size I set for the dynamic disk (on VirtualBox 6.1.10 on Windows 10 1909). Possibly (I deleted the machine and recreated it with a fixed-size disk) it was 10GB. If so, then the reason Mint would not install was that there was not enough disk space.

Yet, even if that was so, the error message does not make sense. For the message says: you need at least this amount to install Mint; so you cannot install it because you have . . that very amount.

Also, that strange error message did seem to suggest one thing, namely a problem with the expandable nature of the disk being communication to the Mint installer. Still, and as I mean to say, that may not have been the case. At the least, though, it provides a further reason to change the error message.

**In sum**: having a dynamic disk may not actually be a problem; but if the maximum size of that disk is less than Mint needs, then the self-contradictory error message one receives makes one think that the dynamic disk _is_ the problem. Still, and evidently enough, more testing is needed.

**Comment by clefebvre** [comment]
Fixed in git.

**Comment by clefebvre** [comment]
Fixed.
