### ISSUE TITLE
Wrong french keyboard when installing Linux Mint MATE 20

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20-beta#6]
When I install Linux Mint MATE 20 in french, the default keyboard proposed is "Français - Français (variante obsolète)".
It's a wrong keyboard, the default keyboard should be "Français - Français (azerty)" because it's the most used keyboard in France :
![good-keyboard](https://user-images.githubusercontent.com/3955499/84588691-f2e1d500-ae29-11ea-9812-7f27ae74f80e.png)

https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1807344

**Comment by enigma131** [comment]
All distros have same default settings. Français - Français is working fine also for azerty (I'm French)

**Comment by InfoLibre** [comment]
"Français - Français (variante obsolète)" is a bad default setting because when you want to write ¤ (with Alt Gr + $ keys), you obtain something else. You don't obtain what is expected with ² and Shift + ² keys too.

**Comment by enigma131** [comment]
Ok it's depending on keyboard, I haven't this symbol on mine's laptop .. so perhaps it's why you have to setup it at install. Can't be generalised I think

**Comment by InfoLibre** [comment]
I think even on your laptop, you will have wrong other keys with "Français - Français (variante obsolète)", make tests with specific keys.
See https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1807344

**Comment by enigma131** [comment]
I cant test it now, i'm on live usb and made a quick setup via setxkbmap fr.
This can be a other request, to have keyboard mapping on live boot, some distros have it.

**Comment by InfoLibre** [comment]
Yes, LMDE shows the keyboard but I'm not sure Ubuntu/Mint is using the same installer software than Debian.
Anyway, it would be better to have "Français - Français (azerty)" by default (or "Français - Français" ?)

**Comment by enigma131** [comment]
If the azerty setting for all fr keyboards is ok why not .... I can't respond, need more contributors with different fr keyboards. My laptop have 89 keys and of course no numeric section

**Comment by InfoLibre** [comment]
I'm using a standard 105 keys keyboard (Genius KB-G235).

**Comment by InfoLibre** [comment]
I just tried a new install in Virtualbox, with choosing Français - Français. With Shift + ² keys, I should obtain nothing, but I obtain ~. So, for a standard 105 keys keyboard, I think Français - Français (azerty) is better, as discussed in https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1807344

**Comment by InfoLibre** [comment]
When I use the button "Detect the keyboard" and answer to the questions, it's the good keyboard that is proposed : "Français - Francais (azerty)".

**Comment by enigma131** [comment]
"Detect the keyboard" on install screen ? Or a Mate specific menu ?

**Comment by InfoLibre** [comment]
Yes, on install screen.

**Comment by enigma131** [comment]
I've launch it without installing. I respond to the questions for detect, and result is french Togo, perhaps because no "oe" key

**Comment by InfoLibre** [comment]
Where did you buy your laptop ?
:o)

**Comment by enigma131** [comment]
In  France lol  :)

**Comment by enigma131** [comment]
I've made more tests on live usb , adding French and French Azerty to English keyboard layout , gives me a icon to select them in panel. I have exactly same characters on sames keys:
&é"'(-è_çà)=°+$£*µ,;:!?./§<>€
&é"'(-è_çà)=°+$£*µ,;:!?./§<>€
So I don't know why you have difference between them. But in conclusion yes, Fr Azerty choice works too for me.

**Comment by InfoLibre** [comment]
Try :
²
SHIFT + ²
¤

**Comment by enigma131** [comment]
Azerty Fr setting : ² ²
Fr setting ²~  
Comment: SHIFT + ²  have no print out on my small keyboard , i don't use it here

**Comment by InfoLibre** [comment]
Azerty Fr is the good choice.

**Comment by enigma131** [comment]
Ok. We'll see If Clem's team can react on this, but my little finger say this part of install is a common install lib used by many distro's, same pictures, and all have same initialisation line, french, french

**Comment by InfoLibre** [comment]
Thank you.
Here is a picture of Français - Azerty keyboard, it's exactly mine and standard 105 keys keyboards :

![Capture du 2020-06-14 18-25-57](https://user-images.githubusercontent.com/3955499/84598661-a23f9b80-ae6c-11ea-83a7-e21afd3878de.png)

**Comment by enigma131** [comment]
Yes this is the standard French keyboard for Desktop. For Laptops, design is mostly completely different, no right key pad, functions keys added etc . The best thing is functions keys are working for Mint on my laptop  (audio volume, brightness, etc).

**Comment by clefebvre** [comment]
I checked that myself for 19.x and I was in France at the time. I remember going to Fnac, Darty and whatnot to actually look at keyboard layouts out there in the market.

The result is: You're right, it should be French - French (no variant).

That said, this is upstream from us. It needs to be reported to Ubuntu (again).

**Comment by InfoLibre** [comment]
> The result is: You're right, it should be French - French (no variant).
No, it should be French - French (azerty), not French - French (no variant).

**Comment by clefebvre** [comment]
@InfoLibre afaik fr (no variant) is the same but it's more complete:

![image](https://user-images.githubusercontent.com/1138515/84762618-f197e000-afc2-11ea-8123-055fea7345cc.png)

If you go to French shops and look at the keyboards and laptops sold there at the moment, they match both layouts.

**Comment by InfoLibre** [comment]
If you want to have the same virtual keyboad than the real french standard 150 keys keyboard, you must choose Français - Français (azerty), not Français - Français (no variant).
¤ key is not on Français - Français (no variant) but is on real french standard keyboard. I'm french and I've got a lot of french keyboard, all standard french keyboard match only Français - Français (azerty). And that's the keyboard that is proposed when you use the button "Detect the keyboard" and answer to the questions during the installation.

**Comment by clefebvre** [comment]
`¤` is there on `Alt-GR + $`.

**Comment by InfoLibre** [comment]
Yes.
