### ISSUE TITLE
MacBook Pro keyboard lights will not stay off with LM20 Mate

### ISSUE THREAD

**Issue by Peter-Nesbitt** [linuxmint/mint20-beta#61]
I have a ~1996 MacBook Pro that works well with LM19.3 Cinnamon and Mate. Loaded-up LM 20 with Cinnamon and Mate last night and found that the lights on my keyboard will not stay off when using LM20 Mate. Everything installed and updated just fine for both versions, but my keyboard lights will not stay off with the Mate version.

I first discovered this while performing some of the updates from the "Welcome" window that first appeared, but then noticed that the keyboard would repeatedly light-up while performing other tasks such as exploring files, downloading files, or simply exploring other functions and features. The keyboard would return to the highest intensity at random times and without any clear indiction as to where, why, or how. Sometimes the keyboard would return to full intensity after a few seconds, while other times it would take a few minutes.

This anomaly does does not exist with Cinnamon. I have not tried XFCE yet.

I tried restarting, rebooting, with and without entering any commands, but the issue persists with Mate.

Could not find the "template" that was mentioned for reporting bugs, so my apologies if this report is not sufficient... please direct me to the correct area or requested format for reporting bugs if this report is incorrectly reported.

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           23
Model name:                      Intel(R) Core(TM)2 Duo CPU     T8300  @ 2.40GHz
Stepping:                        6
CPU MHz:                         1001.608
CPU max MHz:                     2400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4788.48
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        3 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX EPT disabled
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no mic
                                 rocode; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disab
                                 led, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush dts acpi mmx f
                                 xsr sse sse2 ht tm pbe syscall nx lm constant_t
                                 sc arch_perfmon pebs bts rep_good nopl cpuid ap
                                 erfmperf pni dtes64 monitor ds_cpl vmx est tm2 
                                 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm pti tpr_sha
                                 dow vnmi flexpriority dtherm

**Comment by clefebvre** [comment]
I can reproduce it by doing the following:

- Set keyboard backlight to 0%
- Remove power cord
- Wait a bit
- Plug power cord back in

The keyboard backlight goes back to 100%.

This looks relevant: https://github.com/mate-desktop/mate-power-manager/commit/a926d698616666c52586b5778b8cf7fd9ced5b96

We'll pick it up when MATE releases mate-power-manager 1.24.2.
