### ISSUE TITLE
Fractional scale: Screen offset for fullscreen mode (games)

### ISSUE THREAD

**Issue by schluetermichael** [linuxmint/mint20-beta#62]
I've set my screen to 175% fractional scaling (see screenshot) and normal applications just work fine.
![Display Settings](https://user-images.githubusercontent.com/13156489/84736635-96f08b00-afa6-11ea-9d8e-b2da6ea78f3a.png)

However if I use an application in fullscreen mode (i.e. steam game) the screen as an large offset (see screen shot). The mouse has no offset and is therefore not aligned to the visible image. Setting the scale to 100% or 200% does not show this problem.

![Game Fullscreen Offset](https://user-images.githubusercontent.com/13156489/84736643-9c4dd580-afa6-11ea-87c7-18b951396d49.png)

Nvidia Gefore GTX 1060 6GB
Driver 440.64

![Nvidia setting](https://user-images.githubusercontent.com/13156489/84737222-bc31c900-afa7-11ea-8d55-ef2317641b50.png)

inxi:
CPU: 8-Core AMD Ryzen 7 1700X (-MT MCP-) speed/min/max: 1884/2200/3400 MHz 
Kernel: 5.4.0-37-generic x86_64 Up: 17m Mem: 13393.6/32072.6 MiB (41.8%) 
Storage: 2.96 TiB (15.5% used) Procs: 350 Shell: bash 5.0.16 inxi: 3.0.38 

System:    Kernel: 5.4.0-37-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.3 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Desktop System: Dell product: Inspiron 5675 v: 1.3.7 serial: <filter> Chassis: 
           type: 3 v: 1.3.7 serial: <filter> 
           Mobo: Dell model: 0477DV v: A00 serial: <filter> UEFI: Dell v: 1.3.7 date: 03/14/2018 
Battery:   Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard PID:0058 serial: N/A 
           charge: 55% (should be ignored) status: Discharging 
           Device-2: hidpp_battery_1 model: Logitech Wireless Mouse PID:0039 serial: N/A 
           charge: 55% (should be ignored) status: Discharging 
CPU:       Topology: 8-Core model: AMD Ryzen 7 1700X bits: 64 type: MT MCP arch: Zen rev: 1 
           L2 cache: 4096 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 108595 
           Speed: 2191 MHz min/max: 2200/3400 MHz Core speeds (MHz): 1: 2191 2: 2195 3: 1747 
           4: 1747 5: 1745 6: 1742 7: 1745 8: 1745 9: 2196 10: 2191 11: 2189 12: 2194 13: 2192 
           14: 2191 15: 3491 16: 3490 
Graphics:  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] vendor: Dell driver: nvidia v: 440.64 
           bus ID: 09:00.0 chip ID: 10de:1c03 
           Display: x11 server: X.Org 1.20.8 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: 3840x2160~30Hz 
           OpenGL: renderer: GeForce GTX 1060 6GB/PCIe/SSE2 v: 4.6.0 NVIDIA 440.64 
           direct render: Yes 
Audio:     Device-1: NVIDIA GP106 High Definition Audio vendor: Dell driver: snd_hda_intel 
           v: kernel bus ID: 09:00.1 chip ID: 10de:10f1 
           Device-2: AMD Family 17h HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
           bus ID: 0b:00.3 chip ID: 1022:1457 
           Device-3: Logitech Logitech USB Headset type: USB 
           driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-7:2 chip ID: 046d:0a8f 
           Sound Server: ALSA v: k5.4.0-37-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell 
           driver: r8169 v: kernel port: 3000 bus ID: 01:00.0 chip ID: 10ec:8168 
           IF: enp1s0 state: down mac: <filter> 
           Device-2: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter vendor: Dell 
           driver: ath10k_pci v: kernel port: 3000 bus ID: 05:00.0 chip ID: 168c:003e 
           IF: wlp5s0 state: up mac: <filter> 
           Device-3: Qualcomm Atheros type: USB driver: btusb bus ID: 1-12:4 chip ID: 0cf3:e007 
Drives:    Local Storage: total: 2.96 TiB used: 471.07 GiB (15.5%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 970 EVO Plus 1TB size: 931.51 GiB 
           speed: 31.6 Gb/s lanes: 4 serial: <filter> 
           ID-2: /dev/sda vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB speed: 6.0 Gb/s 
           serial: <filter> 
           ID-3: /dev/sdb vendor: SK Hynix model: SC311 SATA 256GB size: 238.47 GiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-4: /dev/sdc vendor: Seagate model: ST1000DM010-2EP102 size: 931.51 GiB 
           speed: 6.0 Gb/s serial: <filter> 
Partition: ID-1: / size: 915.89 GiB used: 471.03 GiB (51.4%) fs: ext4 dev: /dev/nvme0n1p1 
           ID-2: swap-1 size: 38.15 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sdc1 
Sensors:   System Temperatures: cpu: 44.0 C mobo: N/A gpu: nvidia temp: 37 C 
           Fan Speeds (RPM): cpu: 5152 fan-1: fan-2: 510 fan-3: 516 gpu: nvidia fan: 42% 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //mirror.netcologne.de/linuxmint/packages ulyana main upstream import backport
           2: deb http: //mirror2.tuxinator.org/ubuntu focal main restricted universe multiverse
           3: deb http: //mirror2.tuxinator.org/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //mirror2.tuxinator.org/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/spotify.list 
           1: deb http: //repository.spotify.com stable non-free
           Active apt repos in: /etc/apt/sources.list.d/virtualbox.list 
           1: deb https: //download.virtualbox.org/virtualbox/debian focal contrib
           Active apt repos in: /etc/apt/sources.list.d/vscode.list 
           1: deb [arch=amd64] http: //packages.microsoft.com/repos/vscode stable main
Info:      Processes: 363 Uptime: 1m Memory: 31.32 GiB used: 11.64 GiB (37.2%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38

**Comment by clefebvre** [comment]
Hi,

This is upstream from us unfortunately and a limitation between xrandr and the GPU driver. What we'll do is make it clearer fractional scaling is ON and advertise it as an experimental feature with limitations.
