### ISSUE TITLE
l10n: mintupdate tray tooltip

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#64]
In mintupdate applet, when updates are available, if French is system-wide language, it is English words that are displayed.
User can read "4 updates available" but in French it should be : "4 mises à jour disponibles"
![Bug_EN_trans_mintupdate](https://user-images.githubusercontent.com/66995112/84750471-9b736e80-afbb-11ea-89f7-8af5d3d7a9a9.png)

**Comment by clefebvre** [comment]
Fixed in mintupdate 5.6.7.
