### ISSUE TITLE
l10n: Cinnamon printer and notification applets

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#65]
In cinnamon printer applet,

- when you are printing a document, you see : "Printing" instead of "Impression".
and you see "on" instead of "sur".
![Bug Traduction EN](https://user-images.githubusercontent.com/66995112/84750863-22284b80-afbc-11ea-9454-9e542ad0e22c.png)

- when you click on the notification icon in systray, you see "X min ago"  instead of "il y a X minutes"
![Bug traduction](https://user-images.githubusercontent.com/66995112/84751033-60256f80-afbc-11ea-8d01-15cbc99f9847.png)

French words should be displayed.

**Comment by clefebvre** [comment]
Notification issue reproduced.

**Comment by clefebvre** [comment]
Notification issue fixed in git.

**Comment by clefebvre** [comment]
OK... notif bug is fixed in cinnamon 4.6.4.
printing bug is partly fixed in csd 4.6.1, but it will require new translations (before stable). This will happen anyway, as stated on trello, so I'm closing this as fixed for now.
