### ISSUE TITLE
l10n: Cinnamon display settings

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#66]
In Cinnamon Display system settings, there are English words displayed instead of French.
![Cinnamon_Affichage_TransEN-FR](https://user-images.githubusercontent.com/66995112/84751422-d7f39a00-afbc-11ea-94d3-c8cb60daf9af.png)
French words should be displayed.
Where to participate translation?

**Comment by clefebvre** [comment]
Fixed.
