### ISSUE TITLE
l10n: lightdm-settings

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#68]
In org.x.lightdm-settings, in French locale, a translation is missing:
![Ecran_de_connexion_EN](https://user-images.githubusercontent.com/66995112/84753526-62d59400-afbf-11ea-85a4-5f9798789097.png)

User see: "Stretch background across multiple monitors" in English.
it should be in french: "Étirer le fond d'écran sur tous les moniteurs"

**Comment by clefebvre** [comment]
Fixed.
