### ISSUE TITLE
LTS support timeframe different between blog post and release page

### ISSUE THREAD

**Issue by martinseener** [linuxmint/mint20-beta#7]
Just a minor thing I guess, but there is a difference of the LTS support timeframe between the Mint 20 Blog post and release page. First says 2025 and release page says 2023. What is correct?
https://blog.linuxmint.com/?p=3915 (for all three flavours)
https://www.linuxmint.com/rel_ulyana_cinnamon_whatsnew.php

**Comment by xenopeek** [comment]
Looks to have been fixed. 2025 is correct.
