### ISSUE TITLE
org.x.ligthdm complains about wrong settings

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#70]
Each system boot, lightdm complains:
lightdm[894]: Seat type 'xlocal' is deprecated, use 'type=local' instead

This should be upstream.

**Comment by clefebvre** [comment]
Confirmed, this looks upstream. No sign of xlocal anywhere on our side.. I can't find what's providing it though... lightdm considers it obsolete but I'm not sure where it's set.
