### ISSUE TITLE
lightdm: missing kwallet pam module

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#71]
Each user login, lightdm complains about missing kwallet pam module.
journalctl -b:
juin 16 08:49:55 linuxmint lightdm[1032]: PAM unable to dlopen(pam_kwallet.so): /lib/security/pam_kwallet.so: cannot open shared object file: No such file or directory
juin 16 08:49:55 linuxmint lightdm[1032]: PAM adding faulty module: pam_kwallet.so

Linux Mint all version (Cinnamon, Mate and Xfce)
This is also true in latest stable Linux Mint 19.3 version.
It is not stop bug.

**Comment by clefebvre** [comment]
It looks upstream https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/1404172.
