### ISSUE TITLE
Wrong configuration in PAM modules looking for deprecated upstream file securetty

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#72]
Each time you use a sudo command in terminal like this:
$ sudo journalctl -b
 You can see:
juin 16 11:04:56 linuxmint dbus-daemon[1193]: [session uid=1000 pid=1193] Activating via systemd: service name='org.gnome.Terminal' unit='gnome-terminal-server.service' requested by ':1.669' (uid=1000 pid=23805 comm="/usr/bin/gnome-termi>
juin 16 11:04:56 linuxmint systemd[1148]: Created slice apps.slice.
juin 16 11:04:56 linuxmint systemd[1148]: Created slice apps-org.gnome.Terminal.slice.
juin 16 11:04:56 linuxmint systemd[1148]: Starting GNOME Terminal Server...
juin 16 11:04:56 linuxmint dbus-daemon[1193]: [session uid=1000 pid=1193] Successfully activated service 'org.gnome.Terminal'
juin 16 11:04:56 linuxmint systemd[1148]: Started GNOME Terminal Server.
juin 16 11:04:56 linuxmint systemd[1148]: Started VTE child process 23815 launched by gnome-terminal-server process 23808.
**juin 16 11:05:05 linuxmint sudo[23822]: pam_unix(sudo:auth): Couldn't open /etc/securetty: Aucun fichier ou dossier de ce type
juin 16 11:05:08 linuxmint sudo[23822]: pam_unix(sudo:auth): Couldn't open /etc/securetty: Aucun fichier ou dossier de ce type**
juin 16 11:05:08 linuxmint sudo[23822]: aurelien : TTY=pts/0 ; PWD=/home/aurelien ; USER=root ; COMMAND=/bin/journalctl -b
juin 16 11:05:08 linuxmint sudo[23822]: pam_unix(sudo:session): session opened for user root by (uid=0)
PAM modules complains about a missing file which is deprecated upstream.
[https://bugs.launchpad.net/ubuntu/+source/pam/+bug/1860826](https://bugs.launchpad.net/ubuntu/+source/pam/+bug/1860826)

**Comment by clefebvre** [comment]
Closing as upstream.
