### ISSUE TITLE
mintreport: indicator-application breaks SNI support

### ISSUE THREAD

**Issue by thegreatyellow67** [linuxmint/mint20-beta#73]
I'm testing Linux Mint 20 Cinnamon in a Virtualbox machine.
I'm realizing that applications that have a systray icon are not shown (example ClipIt, Owncloud Client, etc). It's a bug or my mistake? Is there any new feature that enables/disables systray icons? Now I only see Update Manager icon, Network icon, Printer icon and Volume icon. Thanks!

![Screenshot from 2020-06-16 11-45-28](https://user-images.githubusercontent.com/41580754/84759346-e5ae1d00-afc6-11ea-88ea-f83a57bc741a.png)

**Comment by aureoud-fr85** [comment]
Hello,
I think this is related to this bug:
xapp-sn-watcher silently hangs signal 11 each system startup and switching user #69
[https://github.com/linuxmint/mint20-beta/issues/69](https://github.com/linuxmint/mint20-beta/issues/69)
Regards,

**Comment by thegreatyellow67** [comment]
Thanks a lot, so will be fixed with the xapp-sn-watcher bug.

**Comment by mtwebster** [comment]
@thegreatyellow67 can you perform the steps I outlined [here](https://github.com/linuxmint/mint20-beta/issues/69#issuecomment-644866910)?

Thakns

**Comment by thegreatyellow67** [comment]
So, the first command:
dpkg --list | grep indicator
returned:
ii  gir1.2-appindicator3-0.1                   12.10.1+20.04.20200408.1-0ubuntu1   amd64        Typelib files for libappindicator3-1.
ii  indicator-applet                           12.10.2+20.04.20200409-0ubuntu1     amd64        GNOME panel indicator applet
ii  indicator-application                      12.10.1+19.04.20190308.1-0ubuntu3   amd64        Application Indicators
ii  indicator-appmenu                          15.02.0+16.10.20160927-0ubuntu5     amd64        Indicator for application menus.
ii  indicator-bluetooth                        0.0.6+17.10.20170605-0ubuntu3       amd64        System bluetooth indicator.
ii  indicator-common                           16.10.0+18.04.20180321.1-0ubuntu4   all          indicator shared files
ii  indicator-datetime                         15.10+20.04.20200217-0ubuntu1       amd64        Simple clock
ii  indicator-keyboard                         0.0.0+19.10.20190716-0ubuntu3       amd64        Keyboard indicator
ii  indicator-messages                         13.10.1+18.10.20180918-0ubuntu2     amd64        indicator that collects messages that need a response
ii  indicator-power                            12.10.6+17.10.20170829.1-0ubuntu5   amd64        Indicator showing power state.
ii  indicator-printers                         0.1.7+17.10.20171101-0ubuntu2       amd64        indicator showing active print jobs
ii  indicator-session                          17.3.20+19.10.20190921-0ubuntu1     amd64        indicator showing session management, status and user switching
ii  indicator-sound                            12.10.2+18.10.20180612-0ubuntu1     amd64        System sound indicator.
ii  libappindicator1                           12.10.1+20.04.20200408.1-0ubuntu1   amd64        Application Indicators
ii  libappindicator3-1                         12.10.1+20.04.20200408.1-0ubuntu1   amd64        Application Indicators
ii  libayatana-appindicator3-1                 0.5.4-2                             amd64        Ayatana Application Indicators (GTK-3+ version)
ii  libayatana-indicator3-7:amd64              0.6.3-1                             amd64        panel indicator applet - shared library (GTK-3+ variant)
ii  libindicator3-7                            16.10.0+18.04.20180321.1-0ubuntu4   amd64        panel indicator applet - shared library

and the second:
gdbus call --session --dest org.freedesktop.DBus --object-path / --method org.freedesktop.DBus.GetConnectionUnixProcessID org.kde.StatusNotifierWatcher
returned:
(uint32 3516,)

so:
giagio@mbox:~$ ps -A | grep 3516
3516 ?        00:00:00 indicator-appli

**Comment by mtwebster** [comment]
You need to uninstall indicator-application.  Most of the indicator applications don't work under Cinnamon either, but indicator-application is blocking XApp's handler from running (causing your icons not to show up).

**Comment by thegreatyellow67** [comment]
As suggested, I've removed package indicator-application and application icons are now visible. As I've installed some packages, I really don't know if one of them has installed indicator-application as dependency, but I think no, because during removing it not suggested me to remove other software related to it.
I would like to investigate further by installing a new virtual machine and check if that package exists in a clean installation.

**Comment by thegreatyellow67** [comment]
As was obvious, the indicator-application package is not present in a clean installation of Mint 20. So, now I will have to investigate which application installs this package. This problem does not exist in my main PC with Mint 19.3 Cinnamon installed. I am afraid to encounter the same problem when I will install Mint 20 on my linux pc.

**Comment by mtwebster** [comment]
There are 2 log files in /var/log/apt, they should show you a history of installations (including dependencies).

**Comment by thegreatyellow67** [comment]
I was just inspecting the /var/log/apt/term.log file...

**Comment by thegreatyellow67** [comment]
I'm not sure but:
Log started: 2020-06-14  21:53:01
Selecting previously unselected package libunity-gtk2-parser0:amd64.
...
Preparing to unpack .../26-indicator-common_16.10.0+18.04.20180321.1-0ubuntu4_all.deb ...
Unpacking indicator-common (16.10.0+18.04.20180321.1-0ubuntu4) ...
Selecting previously unselected package indicator-application.
Preparing to unpack .../27-indicator-application_12.10.1+19.04.20190308.1-0ubuntu3_amd64.deb ...
Unpacking indicator-application (12.10.1+19.04.20190308.1-0ubuntu3) ...

[term.log](https://github.com/linuxmint/mint20-beta/files/4788957/term.log)

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintreport/pull/53

**Comment by clefebvre** [comment]
Ok, fixed in git. We'll send an update when the translations are ready.

**Comment by thegreatyellow67** [comment]
Thanks Mr. LeFebvre.
