### ISSUE TITLE
l10n: cinnamon-session

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#75]
French user can see this when you click on Shutdown or Logout:
![Trans_Session-User](https://user-images.githubusercontent.com/66995112/84766286-d633d180-afd0-11ea-954d-ab67c45495ee.png)
and this:
![Translate_Session-dialog](https://user-images.githubusercontent.com/66995112/84766295-db911c00-afd0-11ea-9cf9-c1cb70d7e709.png)

There is typo-error: [nnsbp] for a unbreakable space character.

**Comment by clefebvre** [comment]
Thanks, this is so annoying... I'll take care of it.

**Comment by clefebvre** [comment]
@mtwebster we might start to flag these in mocheck..

**Comment by clefebvre** [comment]
Similar issue with [nbsp] in mintbackup:

![image](https://user-images.githubusercontent.com/1138515/84790681-87466600-afe9-11ea-913e-4dac092bfffb.png)

**Comment by clefebvre** [comment]
It's not rendered correctly in the command line either:

![image](https://user-images.githubusercontent.com/1138515/84790764-a218da80-afe9-11ea-9d2f-08e7ad37d1fe.png)

**Comment by clefebvre** [comment]
OK, this is tackled by https://github.com/linuxmint/mint-translations/commit/3bbb3d98dcd6a17c8711fb24f048d694377dfea0.

This should please everybody.

Note that nbsp is using a traditional space character for compatibility reason.
nnbsp is given the proper unicode thin space. If this creates issues going forward we'll change that to a normal ascii space char as well.

**Comment by clefebvre** [comment]
In Mint 20, there will be new translations coming up for all projects, so this will roll out as package updates before the stable release.

**Comment by aureoud-fr85** [comment]
Best for all,
Have a lot of fun!
