### ISSUE TITLE
Error activating XKB configuration

### ISSUE THREAD

**Issue by karel1** [linuxmint/mint20-beta#77]
![Screenshot at 2020-06-16 14-08-06](https://user-images.githubusercontent.com/3692937/84773701-1a2cd380-afdd-11ea-86e7-2c5474eb8b66.png)

xprop -root |grep XKB
_XKB_RULES_NAMES_BACKUP(STRING) = "evdev", "pc105", "us", "mac", ""
_XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "mac", "terminate:ctrl_alt_bksp"
gsettings list-keys org.mate.peripherals-keyboard-xkb.kbd
layouts
options
model

**Comment by karel1** [comment]
Error went away after selecting another Apple Keyboard Model. If it's just me, issue can be closed.

**Comment by clefebvre** [comment]
How do you make this happen?

**Comment by karel1** [comment]
![Screenshot at 2020-06-17 20-43-15](https://user-images.githubusercontent.com/3692937/84936913-475fab80-b0db-11ea-8372-fe3441422db0.png)
Change keyb model to 'Apple Aluminium (JIS)' and error is gone. (Not with same (Ansi) or (ISO))

**Comment by clefebvre** [comment]
Thanks @karel1 this is upstream from us.
