### ISSUE TITLE
Num lock key

### ISSUE THREAD

**Issue by John-Mike974** [linuxmint/mint20-beta#78]
Hello everyone,
Not a big deal, I noticed that I've to push twice the num lock key to activate it after an automatic screen lock (enter the password).
Thank you for mint

**Comment by aureoud-fr85** [comment]
Hello @John-Mike974 
I can't reproduce you're report.
Even with auto lock function, and numlock deactivated before going into lock screen, and even with manual locking.
For each case, numlock activates with just one key.
Cinnamon version tested.
Regards,
