### ISSUE TITLE
Grub Boot Select despite only single OS

### ISSUE THREAD

**Issue by bennihtm** [linuxmint/mint20-beta#79]
I recently installed the Linux Mint 20 beta, clean. I don't do dual boot with windows or any other OS.
But the Grub Boot Selector still pops up, every time I boot.
On Linux Mint 19.3 that wasn't the case.

**Comment by clefebvre** [comment]
Yes, this is in the new features page, it's by design. I'm seeing people in the blog wondering about this as well. We might add a page in the user guide to explain how to disable it.
