### ISSUE TITLE
Numlock package is not install by default

### ISSUE THREAD

**Issue by mauricejl** [linuxmint/mint20-beta#81]
Hello, 
Add numlockx package by default in all linuxmint edition.
I use to install  LM for many years and each time, I install it.

Thank you very much.

Jean-Luc

**Comment by aureoud-fr85** [comment]
:+1: 
numlockx package should be default. It is also required for org.x.lightdm to have the function being toggled in system-preferences interface.
In org.x.ligthdm-settings GUI application, in "Options" tab, I think that, for inexperienced newcomers, it may be difficult to install the package themselves.
![numlockx_not_default](https://user-images.githubusercontent.com/66995112/84893210-28dbbf00-b09f-11ea-8854-77c88a8a6e56.png)
If a GUI relies upon an other binary to store a setting, this tool must be a dependence.
Regards,

**Comment by mauricejl** [comment]
Hello,
I'm just an advanced user and I install regularly LM Mate on PC desktops
with large keyboard (with numeric key pad)
At each installation, if I want to have the numlock function active at
power on,like many users
in Menu - Control Center - Login Window, I set "Activate numlock" to ON
I have to install sudo apt-get install numlockx otherwise the option is not
available.
*numlockx_1.2-8_amd64.deb is only 8.6kB*,

Why numlockx is not install by default?

Don't forget LinuxMint is design to be sample as possible 😉

Jean-Luc

**Comment by aureoud-fr85** [comment]
:+1:

**Comment by clefebvre** [comment]
It's not installed by default because it prevents some people from typing some characters on some small keyboards.
