### ISSUE TITLE
Attempting to change printer driver freezes Printers app

### ISSUE THREAD

**Issue by jbergengh** [linuxmint/mint20-beta#82]
In the Printers app, Right click on a printer and click "Properties"
To the right of "Make and Model" click the "Change" button.
The Change Driver window opens, and the app freezes.

Same condition happens in Ubuntu.

**Comment by xenopeek** [comment]
The Printers app is `system-config-printer` package from focal repository. As you also say the same happens in Ubuntu this looks to be an upstream issue.

Possibly related: https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/1883370

I work paperless so can't confirm but a workaround may be to go to address `localhost:631` in your web browser and add the printer through the CUPS web interface.
