### ISSUE TITLE
Gdebi lacking useful screens

### ISSUE THREAD

**Issue by davidbannon** [linuxmint/mint20-beta#86]
To quote release page - "Gdebi, the tool used to open and install .deb files was given a new user interface."

In fact, what appears to have happened is some very useful information has been removed from GDebi with no benefit. 

As a developer, I encourage users to use gdebi and to look at the pages it presents before installing, but with the version of gdebi in Mint 20 we cannot easily see developer contact details, we cannot confirm the version number, we cannot even see the installed size.  And we cannot see the linian output, of great interest to a developer and arguably an indication of how 'compliant' a package is with Debian rules.  

Otherwise, great looking release, congratulations folks.

Davo

**Comment by xenopeek** [comment]
This isn't so much a beta bug as a feature request to add the Lintian output tab; the other information you say is missing is in fact shown. Noted as such. Previous version of GDebi on Linux Mint didn't have the Lintian output tab either. If you prefer GDebi with Lintian output tab you can install it on Linux Mint 20 with this command:

`apt install gdebi/focal gdebi-core/focal`

To revert to the Linux Mint 20 GDebi run:

`apt install gdebi/ulyana gdebi-core/ulyana`

Aside from the Lintian output tab the same information, as far as I can see, is shown in Linux Mint 20 GDebi version:

- The version number is shown in the titlebar underneath the package name.
- The maintainer and installed size are shown just above the package description.
- For the includes files click the button to the left of the Install Package button.
- When installing a package clicking the ⏵Details displays the terminal output.

**Comment by NikoKrause** [comment]
![gdebi](https://user-images.githubusercontent.com/8415124/84887724-7c95da80-b096-11ea-90ea-dcc09a02560b.png)

> with the version of gdebi in Mint 20 we cannot easily see developer contact details, we cannot confirm the version number, we cannot even see the installed size.

We are blind?

**Comment by davidbannon** [comment]
Thanks xenopeek for your polite and helpful reply.  I only looked at it for a few seconds before the VM I was testing in crashed, permanently.  It was long enough to see things things were not where I expected them to be.  And I was not inclined to build another VM if its going to become unusable when I alter (virtual) screen size.  

I am not sure I would regard requesting Lintian output as a Feature Request, more a revert an unnecessary change request :-)

And thanks Niko, your comment makes it easy for me to walk away from Linux Mint with out thinking I did not give you a fair chance.

Davo

**Comment by NikoKrause** [comment]
Sorry I didn't meant to be rude. You just had seconds to look at it before your VM crashed. You probably missed the screenshot on the release page under the text you quoted:
![Screenshot_20200618_115653](https://user-images.githubusercontent.com/8415124/85007036-3f475080-b15b-11ea-943c-337d621d0997.jpg)

**Comment by davidbannon** [comment]
No Niko, you were quite right to point out that I had not confirmed the details and I should have before posting. And I should not have taken a poke at you, I am sorry. I was having a bad day but that is absolutely no excuse !

Linux Mint is a great looking product, I sincerely wish Ubuntu put as much effort into its presentation.

Davo
