### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by linuxlover7** [linuxmint/mint20-beta#87]
I am using XFCE and Thunar as my file manager however it appears that it does not matter what file manager I use, the problem is the same either way.  I have not used any other DE but that is not to say that the problem only exists in XFCE.

The problem is that small files will have thumbnails generated for them automatically when the folder is opened but larger files such as 4GB files will not get thumbnails generated.  To reproduce this issue, find or create a 4GB file.

The easiest way is to turn on a camera and record till it forces you to stop recording.  (Most cameras stop recording at 4GB.)  Import that to your computer and see that no thumbnail is generated.

Please note that I have not rigorously tested this bug to find out exactly when a thumbnail will no longer be generated but I can say that a 4GB file will not get a thumbnail generated but I don't know exactly where the cut off is for when Mint will no longer create a thumbnail.  Perhaps the cut off is 3GB or 2GB.  I don't know.  I haven't gotten the time to create files of incremented sizes to find out exactly when this bug will first manifest itself.

**Comment by xenopeek** [comment]
Xfce uses Tumbler to generate thumbnails. Tumbler has a default max file size for each of the supported file formats, above which it won't generate thumbnails. See the `/etc/xdg/tumbler/tumbler.rc` configuration file on your system. For example it won't generate thumbnails for PDF files larger than about 200 MB or for video files larger than 2 GB. You can reconfigure Tumbler as per your needs. For more information see: https://docs.xfce.org/xfce/thunar/tumbler
