### ISSUE TITLE
MATE First use of sudo in terminal slow

### ISSUE THREAD

**Issue by GilbertDube** [linuxmint/mint20-beta#88]
The first sudo command (only the first one) take ~25s to execute.
PC usage stay at 2%
ex: sudo caja
or: sudo xed /etc/fstab
Afterward any command will execute fast.
Did not see that behavior in Cinnamon (VM)

**Added this Auth.log capture of when it happen.**

![Screenshot at 2020-06-17 12-45-49](https://user-images.githubusercontent.com/19807875/84926002-466a5200-b0ba-11ea-8b68-062a6c586f5e.png)

![MySysShot](https://user-images.githubusercontent.com/19807875/84843687-18dcc480-b038-11ea-8684-eccc87fd7aa2.png)

**Comment by xenopeek** [comment]
I can't reproduce this on LM20 MATE. Was this a one-off issue for you or can you reproduce it? Can you add some detail to when exactly the issue happens (e.g., first time after log in, every time you open a new terminal in the same log in, or ...).

Note also that you should probably not be using `sudo` with GUI programs. Instead use what polkit provides to doing administrative tasks. E.g. run `pkexec caja` to run Caja as root and run `xed admin:///etc/fstab` to edit /etc/fstab as root.

**Comment by GilbertDube** [comment]
Hi xenopeek, _thank you for your time_.

The problem appears every time I restart, but only the first time I enter an command inside a terminal.
All subsequent command are normal.

I reinstalled several times and tested all day.
I found this in my startup script:

_nvidia-settings -a [gpu: 0] / GPUFanControlState = 1 -a [fan-0] / GPUTargetFanSpeed = 65_

**when I remove it, I have no more delay,
when I put it back, the problem reappears.**

I have the 440.64 NVIDIA driver installed.
My xorg.conf:

:nvidia-settings: X configuration file generated by nvidia-settings
:nvidia-settings:  version 440.64

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0" 0 0
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
    Option         "Xinerama" "0"
EndSection

Section "Files"
EndSection

Section "Module"
    Load           "dbe"
    Load           "extmod"
    Load           "type1"
    Load           "freetype"
    Load           "glx"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    # HorizSync source: edid, VertRefresh source: edid
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "BenQ XL2730Z"
    HorizSync       222.0 - 222.0
    VertRefresh     40.0 - 144.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BoardName      "GeForce GTX 1050 Ti"
    Option         "Coolbits" "4"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "Stereo" "0"
    Option         "nvidiaXineramaInfoOrder" "DFP-2"
    Option         "metamodes" "DP-0: 2560x1440_60 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On, AllowGSYNC=Off}, HDMI-0: 1920x1080_60 +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
    Option         "SLI" "Off"
    Option         "MultiGPU" "Off"
    Option         "BaseMosaic" "off"
    Option         "Coolbits" "4"
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
