### ISSUE TITLE
Documenting how to hide the grub menu may not be enough

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mint20-beta#89]
The Trello board has an [item](https://trello.com/c/87qjr1dd/107-doc-document-how-to-hide-grub-menu) that reads, 'Document how to hide grub menu'. That may be insufficient. For, lots of people will want to hide that menu. For, it slows boot, will confuse some people and arguably looks bad.[1]

So, given that you are keen on showing the menu, why not add a 'System Report' or 'First Steps' item that allows the user to hide the menu?

Also: that you did not even initially think to document how to hide the menu is somewhat worrying. For, this is a conspicuous change that, as I say, one can expect many users to dislike. And not all of your users are especially technical. They won't know how to do `sudo nano <whatever the pertinent grub file is>` or to install and use `grub-customizer`.

[1] On some configurations, especially default ones and especially perhaps on VirtualBox, the Grub menu looks really bad, partly but not entirely because of low resolution.

**Comment by clefebvre** [comment]
Reverted.
Doc added: https://linuxmint-user-guide.readthedocs.io/en/latest/grub.html
