### ISSUE TITLE
Mint Mate 20 - Menu without program entries

### ISSUE THREAD

**Issue by Jildridge** [linuxmint/mint20-beta#9]
On a laptop with integrated amdgpu R2:

Concerning Mate Edition: In Mate-Menu there are categories visible only, whereas no program entries are displayed. Its permanent. In live edition the menues are complete.

**Comment by clefebvre** [comment]
Can you show a screenshot?

**Comment by Jildridge** [comment]
I'm currently reinstalling .... and will send a screenshot asap.

**Comment by Jildridge** [comment]
Well after reinstallation (by using German language) now the menus seem to work, however the previous installation was done with an instable  internet connection. Maybe that led to some problems during the installation process, espec. when downloading language packages?

BTW: Screenshot is not available (nothing happens when pressing the print button as usual) but I think there is already an issue about it.

Thanks anyway for your help and your work.

**Comment by clefebvre** [comment]
Cool, reopen an issue if you can reproduce it again.
