### ISSUE TITLE
Upstream Error: 'initramfs unpacking failed: Decoding failed' with proposed 'fix' (not by me)

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint20-beta#90]
Ubuntu 19.10, Ubuntu 20.04, and Linux Mint 20 by default use compress=lz4 in the /etc/initramfs-tools/initramfs.conf which causes the error. The error can be seen during boot, via the Logs application and by executing the command `journalctl -p 3 -xb` in the terminal. The issue has been reported as a bug in launchpad in this link:  [ initramfs unpacking failed](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1835660). A way to 'fix' the issue for now is to set compress=gzip instead of the default compress=lz4 in the /etc/initramfs-tools/initramfs.conf as provided by user vmc (vmclark)  in [comment 11](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1835660/comments/11) in the bug report and then executing `sudo update-initramfs -u` in the terminal. After reboot the error is gone.

**Comment by clefebvre** [comment]
Thanks Tony. Hopefully this will be fixed in 20.04 at some stage. This is indeed upstream from us.
