### ISSUE TITLE
Driver Manager causing crash

### ISSUE THREAD

**Issue by mcoult** [linuxmint/mint20-beta#91]
Driver manager recommended loading nvidia 440 for my K420 card instead of the the open source video-nouveau but failed to download

Failed to download package file

Code: Select all

Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6_2.31-0ubuntu9_i386.deb 
Could not open file /var/cache/apt/archives/partial/libc6_2.31-0ubuntu9_i386.deb - 
open (13: Permission denied) [IP: 91.189.88.152 80]

Failed to fetch http://archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-440/libnvidia-cfg1-440_440.82+really.440.64-0ubuntu6_amd64.deb
Could not open file /var/cache/apt/archives/partial/libnvidia-cfg1-440_440.82+really.440.64-0ubuntu6_amd64.deb - 
open (13: Permission denied) [IP: 91.189.88.142 80]

Failed to fetch http://archive.ubuntu.com/ubuntu/pool/restricted/n/nvidia-graphics-drivers-440/nvidia-driver-440_440.82+really.440.64-0ubuntu6_amd64.deb
Could not open file /var/cache/apt/archives/partial/nvidia-driver-440_440.82+really.440.64-0ubuntu6_amd64.deb - 
open (13: Permission denied) [IP: 91.189.88.152 80]

tried to install but then Driver Manager and Software manager would not open when clicked, eventually whole system hung while logging into Mint Forum

Had to hard stop the computer and restart and still same symptoms so used Timeshift to restore point.

Now all working but still cant update Nvidia driver manager without repeating the cycle

**Comment by mcoult** [comment]
Not sure if this helps but herewith the system specs

System:    Kernel: 5.4.0-37-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.6.3 
           wm: muffin dm: LightDM Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal 
Machine:   Type: Desktop System: Dell product: Precision Tower 3620 v: N/A serial: <filter> 
           Chassis: type: 3 serial: <filter> 
           Mobo: Dell model: 09WH54 v: A00 serial: <filter> UEFI: Dell v: 2.13.1 date: 06/14/2019 
CPU:       Topology: Quad Core model: Intel Core i7-6700 bits: 64 type: MT MCP arch: Skylake-S 
           rev: 3 L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 54398 
           Speed: 3796 MHz min/max: 800/4000 MHz Core speeds (MHz): 1: 3782 2: 3747 3: 3700 
           4: 3792 5: 3796 6: 3703 7: 3745 8: 3788 
Graphics:  Device-1: Intel HD Graphics 530 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:1912 
           Device-2: NVIDIA GK107GL [Quadro K420] driver: nouveau v: kernel bus ID: 01:00.0 
           chip ID: 10de:0ff3 
           Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: NVE7 v: 4.3 Mesa 20.0.4 direct render: Yes 
Audio:     Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:a170 
           Device-2: NVIDIA GK107 HDMI Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           chip ID: 10de:0e1b 
           Device-3: Texas Instruments PCM2704 16-bit stereo audio DAC type: USB 
           driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-5:2 chip ID: 08bb:2704 
           Sound Server: ALSA v: k5.4.0-37-generic 
Network:   Device-1: Intel Ethernet I219-LM vendor: Dell driver: e1000e v: 3.2.6-k port: f040 
           bus ID: 00:1f.6 chip ID: 8086:15b7 
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 7.86 TiB used: 970.72 GiB (12.1%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: MZVPV128HDGM-00000 size: 119.24 GiB 
           speed: 31.6 Gb/s lanes: 4 serial: <filter> 
           ID-2: /dev/sda vendor: Toshiba model: HDWE140 size: 3.64 TiB speed: 6.0 Gb/s 
           serial: <filter> 
           ID-3: /dev/sdb vendor: Samsung model: SSD 850 PRO 512GB size: 476.94 GiB 
           speed: 6.0 Gb/s serial: <filter> 
           ID-4: /dev/sdc vendor: Toshiba model: HDWE140 size: 3.64 TiB speed: 6.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 29.00 GiB used: 9.18 GiB (31.7%) fs: ext4 dev: /dev/nvme0n1p4 
           ID-2: swap-1 size: 97.66 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sdc9 
Sensors:   System Temperatures: cpu: 35.0 C mobo: 35.0 C gpu: nouveau temp: 46 C 
           Fan Speeds (RPM): cpu: 1064 mobo: 1404 gpu: nouveau fan: 3090 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com ulyana main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 269 Uptime: 18h 49m Memory: 31.26 GiB used: 5.18 GiB (16.6%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38

**Comment by clefebvre** [comment]
Is this still happening? It looks like a networking or repository issue?

**Comment by mcoult** [comment]
Yep you are right.

Soon after I logged the entry a tree came down and took the telephone line down, so it had been working way at the connection as I was trying to install the drivers. Lines reinstated and now drivers installed

Many thanks and apologies for blaming Mint 20, its a dream to work on, well done
