### ISSUE TITLE
Can't set the region or network time - Mint 20 Cinnamon

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint20-beta#92]
I booted Mint 20 Cinnamon 64-bit as a live system from USB.
There I can’t set the date and time. Neither the region  (for me Europe, Berlin) nor the network time are saved.

**Comment by mtwebster** [comment]
I can't reproduce this - the view starts out with no region set.  I can set a region and turn on network time and it saves these values.  I am unable to manually set the time until I close and reopen settings, at which point turning off network time properly reveals the time adjustment.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon/commit/92b5c87c937212a96bd2e367df5f3c3d15b19e8b

This allows the module to finish loading (including being able to set the date/time manually.)

**Comment by jakoblm** [comment]
Thank you. Can it be merged with the ISO's?
