### ISSUE TITLE
Libre Office does not start in live system - Mint 20 Cinnamon

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint20-beta#94]
I booted Mint 20 Cinnamon 64-bit as a live system from USB. 
There **LibreOffice** does not start. A message shows “Fatal exception: Signal 11” referring to many directories in /usr/lib/libreoffice.

**Comment by xenopeek** [comment]
Can't reproduce this yet. How do you start LibreOffice, from the menu or?

Could you try from a fresh boot and start it as such from terminal: `libreoffice --writer`. If there are any messages on the terminal share those here (you can select and copy text from terminal through its Edit menu). Or some dialog is shown with an error, screenshot that.

**Comment by jakoblm** [comment]
It works now. I'm very sorry that I was wrong. 
But I don't know what was going on there either. Now tested it on another computer.
