### ISSUE TITLE
i10n network@cinnamon.org offline notification

### ISSUE THREAD

**Issue by aureoud-fr85** [linuxmint/mint20-beta#96]
In Mint 20 Cinnamon with French locale, when network connection is unavailable, upon a restart from suspend, or manually switching toggle in the applet, you see this:
![i10n-Network-applet](https://user-images.githubusercontent.com/66995112/84895029-0e571500-b0a2-11ea-8683-b8b5e14bb9e2.png)
You see English-only message.

When network becomes reachable, you see correct localized message like this:
![i10n-Network-applet-correct](https://user-images.githubusercontent.com/66995112/84895117-2a5ab680-b0a2-11ea-8cf0-aaa6a4a18149.png)

These messages can be seeing with wired and wireless connections.

Regards,

**Comment by clefebvre** [comment]
Fixed.
