### ISSUE TITLE
Update Manager - "Could not install the security updates"

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/mint20-beta#99]
Failed on the first update after a fresh install where the apt cache had been cleared.
Please see the two related issues reported previously for reference:

https://github.com/linuxmint/mintupdate/issues/583
https://github.com/linuxmint/mintupdate/issues/594

Note:  Here in the U.S. there is no mirror for deb http://security.ubuntu.com/ubuntu/
Could the intermittent nature of the failure be a latency issue?

![Screenshot from 2020-06-17 11-01-08](https://user-images.githubusercontent.com/45599505/84916344-f7a5c380-b08b-11ea-8bef-cb64fd9062b3.png)

**Comment by enigma131** [comment]
I've got a update for mintupdate on my remanent Usb stick today , was it the case for you before posting ?
![mintupdate](https://user-images.githubusercontent.com/31815445/84928010-399b2d80-b0bd-11ea-8384-2939cee62a5b.png)
After mint update, i got a fresh list, updated too, here list extracted from synaptic:
![updates](https://user-images.githubusercontent.com/31815445/84931346-32c2e980-b0c2-11ea-9c36-ac93c4b71003.png)

**Comment by Acheron17** [comment]
This is for a completely different issue going on since last summer.  After the update, the update manager does not close and shows the message at the bottom.  After you do a refresh, it goes away.  I referenced the two issues for anyone to be familiar with the issue.  It is intermittent and has been hard to fix.  I believe there is a commit to fix it but it has not been merged.

**Comment by jakoblm** [comment]
There seems to be a fix: https://github.com/linuxmint/mintupdate/pull/624/files

**Comment by Acheron17** [comment]
Yes, I am using that fix in LMDE 4.  Copied the proposed merge lines into the mintUpdate.py file.  Haven't seen the issue there yet.  But there are not many updates in LMDE 4.  I did not make any changes in the mintUpdate.py file for the LM 20 Beta because other lines were changed and wanted to see if the failure happened again in the LM 20 Beta.

**Comment by clefebvre** [comment]
That's not a fix, it's a workaround, it refreshes again when the problem occurs.

**Comment by Acheron17** [comment]
Is there any idea yet what might be the cause?  I did manually apply Claudiux's commit manually to one system and haven't seen the issue since.

**Comment by clefebvre** [comment]
Fixed in 5.6.8.
